// Package customize defines SpeechKit's public Words/Replacements contract.
package customize

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"strings"
	"time"
)

// Kind is the closed discriminator that says what a [Replacement] produces
// when its match fires. Compare values after [NormalizeKind].
type Kind string

// Replacement kinds. The set is closed by the Words and Replacements
// standard; adding a kind is a standard change, not a local extension.
const (
	// KindSubstitution rewrites the match to Output.Text; an empty output
	// deletes the match (filler-word stripping).
	KindSubstitution Kind = "substitution"
	// KindSynonym normalizes a spoken or written variant to one preferred
	// form; Output.Text is required.
	KindSynonym Kind = "synonym"
	// KindSnippet expands a short trigger into a static text block.
	KindSnippet Kind = "snippet"
	// KindCommand emits Output.Intent and Payload as an action instead of
	// rewriting text.
	KindCommand Kind = "command"
	// KindTemplate renders Output.Template (Go text/template) for Assist
	// and Summarize flows; it is unrelated to the Native Template catalog.
	KindTemplate Kind = "template"
)

// Stage names the point in the voice pipeline at which a [Replacement]
// applies. A resolve [Context] with a Stage keeps only rules of that stage.
type Stage string

// Pipeline stages in processing order.
const (
	// StagePreRecognitionCleanup cleans recognition input before it is
	// recognized.
	StagePreRecognitionCleanup Stage = "pre_recognition_cleanup"
	// StagePostSTT transforms the transcript right after speech-to-text;
	// Dictation and Assist apply this stage, and derived synonym rules
	// default to it.
	StagePostSTT Stage = "post_stt"
	// StagePostLLM transforms text generated by an LLM step.
	StagePostLLM Stage = "post_llm"
	// StageOutput transforms the final text before it leaves SpeechKit.
	StageOutput Stage = "output"
)

// Mode is one of SpeechKit's three voice modes. A [Replacement] lists the
// modes it applies to; an empty list means every mode.
type Mode string

// Voice modes; [NormalizeMode] also accepts common aliases.
const (
	ModeDictation  Mode = "dictation"
	ModeAssist     Mode = "assist"
	ModeVoiceAgent Mode = "voice_agent"
)

// ScopeKind is the layer a customization record belongs to. The resolver
// walks a [Context].ScopeOrder from lowest to highest precedence and lets
// later layers override earlier ones by identity.
type ScopeKind string

// Scope layers in default precedence order, lowest first. Org, workspace,
// user, and session layers address one concrete instance through
// [ScopeRef].Key or the caller's storage scope.
const (
	// ScopeBuiltin holds the curated Native Template packs SpeechKit ships.
	ScopeBuiltin ScopeKind = "builtin"
	// ScopeApp holds records the embedding application provides.
	ScopeApp ScopeKind = "app"
	// ScopeInstall holds records of one installation, keyed by install ID.
	ScopeInstall ScopeKind = "install"
	// ScopeOrg holds records of one organization (tenant); "tenant" is an
	// accepted alias.
	ScopeOrg ScopeKind = "org"
	// ScopeWorkspace holds records of one named workspace.
	ScopeWorkspace ScopeKind = "workspace"
	// ScopeUser holds records of one user.
	ScopeUser ScopeKind = "user"
	// ScopeSession holds records of one session and overrides every other
	// layer.
	ScopeSession ScopeKind = "session"
)

// ScopeRef selects one customization layer. Key names the concrete
// install, org, workspace, user, or session; when empty, the resolver
// derives it from the caller's storage scope where it can and skips the
// layer otherwise.
type ScopeRef struct {
	Kind ScopeKind `json:"kind"`
	Key  string    `json:"key,omitempty"`
}

// MatchType says how [Match].Pattern is interpreted when a rule compiles.
type MatchType string

// Match types; [NormalizeMatchType] treats an empty type as [MatchPhrase].
const (
	// MatchLiteral matches the pattern verbatim, on word boundaries only
	// when Match.WordBoundary is set.
	MatchLiteral MatchType = "literal"
	// MatchPhrase matches the pattern verbatim and always on word
	// boundaries. It is the default.
	MatchPhrase MatchType = "phrase"
	// MatchRegex compiles the pattern as a Go regular expression.
	MatchRegex MatchType = "regex"
	// MatchSpokenAlias is a word-bounded spoken form (mishear) of a [Word];
	// such rules fold into and derive from Word.SoundsLike.
	MatchSpokenAlias MatchType = "spoken_alias"
)

// Match is the trigger of a [Replacement]. Matching is case-insensitive
// unless CaseSensitive is set; WordBoundary makes a literal pattern match
// whole words only (phrase and spoken-alias patterns always do).
type Match struct {
	Type          MatchType `json:"type"`
	Pattern       string    `json:"pattern"`
	CaseSensitive bool      `json:"case_sensitive,omitempty"`
	WordBoundary  bool      `json:"word_boundary,omitempty"`
}

// ReplacementOutput is what a [Replacement] produces; which fields matter
// depends on its [Kind]. Text is the rewrite for substitution, synonym, and
// snippet rules, Intent and Payload describe a command action, and
// Template is a Go text/template (data: ID, Kind, Input, Match, Intent,
// Payload) that takes precedence over Text when set.
type ReplacementOutput struct {
	Text     string         `json:"text,omitempty"`
	Intent   string         `json:"intent,omitempty"`
	Template string         `json:"template,omitempty"`
	Payload  map[string]any `json:"payload,omitempty"`
}

// Word is declarative recognition knowledge: a term STT and LLM providers
// should know. It never rewrites text itself; each SoundsLike alias is
// materialized into a synonym [Replacement]. Language is a primary-language
// prefix (empty means all languages), Weight an optional boost (>= 0)
// mapped to provider scales where supported, Scope says where the Word
// applies and Source where it came from ("settings", "api", "pack:<id>",
// and so on).
type Word struct {
	ID         string    `json:"id"`
	Term       string    `json:"term"`
	SoundsLike []string  `json:"sounds_like,omitempty"`
	Language   string    `json:"language,omitempty"`
	Weight     float64   `json:"weight,omitempty"`
	Tags       []string  `json:"tags,omitempty"`
	Scope      *ScopeRef `json:"scope,omitempty"`
	Source     string    `json:"source,omitempty"`
	Enabled    bool      `json:"enabled"`
	UsageCount int       `json:"usage_count,omitempty"`
	CreatedAt  time.Time `json:"created_at,omitempty"`
	UpdatedAt  time.Time `json:"updated_at,omitempty"`
}

// Replacement is a deterministic transformation rule: when Match fires at
// Stage in one of Modes (empty means every mode), produce Output according
// to Kind. Rules apply in descending Priority with ID as tie-breaker; a
// tagged rule is active only when its Tags intersect the resolve [Context].
// Scope says where the rule applies and Source where it came from.
type Replacement struct {
	ID         string            `json:"id"`
	Kind       Kind              `json:"kind"`
	Match      Match             `json:"match"`
	Output     ReplacementOutput `json:"output"`
	Language   string            `json:"language,omitempty"`
	Modes      []Mode            `json:"modes,omitempty"`
	Stage      Stage             `json:"stage"`
	Priority   int               `json:"priority,omitempty"`
	Tags       []string          `json:"tags,omitempty"`
	Source     string            `json:"source,omitempty"`
	Scope      *ScopeRef         `json:"scope,omitempty"`
	Enabled    bool              `json:"enabled"`
	UsageCount int               `json:"usage_count,omitempty"`
	CreatedAt  time.Time         `json:"created_at,omitempty"`
	UpdatedAt  time.Time         `json:"updated_at,omitempty"`
}

// Lexicon is a named collection of [Word] records referenced by ID. Name
// is required; a store assigns a [StableID] when ID is empty.
type Lexicon struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description,omitempty"`
	Language    string    `json:"language,omitempty"`
	WordIDs     []string  `json:"word_ids,omitempty"`
	Tags        []string  `json:"tags,omitempty"`
	Source      string    `json:"source,omitempty"`
	Scope       *ScopeRef `json:"scope,omitempty"`
	Enabled     bool      `json:"enabled"`
	CreatedAt   time.Time `json:"created_at,omitempty"`
	UpdatedAt   time.Time `json:"updated_at,omitempty"`
}

// Ruleset is a named collection of [Replacement] records referenced by ID.
// Name is required; a store assigns a [StableID] when ID is empty.
type Ruleset struct {
	ID             string    `json:"id"`
	Name           string    `json:"name"`
	Description    string    `json:"description,omitempty"`
	Language       string    `json:"language,omitempty"`
	ReplacementIDs []string  `json:"replacement_ids,omitempty"`
	Tags           []string  `json:"tags,omitempty"`
	Source         string    `json:"source,omitempty"`
	Scope          *ScopeRef `json:"scope,omitempty"`
	Enabled        bool      `json:"enabled"`
	CreatedAt      time.Time `json:"created_at,omitempty"`
	UpdatedAt      time.Time `json:"updated_at,omitempty"`
}

// Context selects the active customization set for one resolve or apply
// call. Language, Mode, and Stage filter records (language-neutral records
// and rules without modes always match), Tags activates tagged records
// whose tags intersect, ActiveTemplateIDs adds Native Template packs, and
// ScopeOrder lists scope layers from lowest to highest precedence (hosts
// fall back to [DefaultDeviceScopeOrder] or [DefaultServerScopeOrder] when
// empty). Persona names the active persona for persona-bound collections.
type Context struct {
	Mode              Mode       `json:"mode,omitempty"`
	Language          string     `json:"language,omitempty"`
	Stage             Stage      `json:"stage,omitempty"`
	Tags              []string   `json:"tags,omitempty"`
	Persona           string     `json:"persona,omitempty"`
	ActiveTemplateIDs []string   `json:"active_template_ids,omitempty"`
	ScopeOrder        []ScopeRef `json:"scope_order,omitempty"`
}

// ListOptions filters store reads of Words, Replacements, Lexicons, and
// Rulesets within the storage scope carried by the context. Language keeps
// records of that language plus language-neutral ones (empty keeps all),
// Mode and Stage apply to Replacements only, Source keeps one origin, and
// disabled records are omitted unless IncludeDisabled is set. Tags carries
// the resolve context tags; the resolver re-checks tag matches on returned
// rows.
type ListOptions struct {
	Language        string
	Mode            Mode
	Stage           Stage
	IncludeDisabled bool
	Source          string
	Tags            []string
}

// ReplaceOptions addresses one replace or import slice: only rows sharing
// the storage scope of the context, Language, and Source are deleted and
// rewritten. An empty Source means "settings".
type ReplaceOptions struct {
	Language string
	Source   string
}

// Pack is the portable, versioned interchange format for Words,
// Replacements, Lexicons, Rulesets, and free-form JSON Attachments.
// SchemaVersion must be empty or [PackSchemaVersion]. Imports derive a
// "pack:<id>" Source from ID (or Name), so re-importing a pack replaces
// only the rows of the same scope, source, and language.
type Pack struct {
	SchemaVersion string          `json:"schema_version"`
	ID            string          `json:"id,omitempty"`
	Name          string          `json:"name,omitempty"`
	Description   string          `json:"description,omitempty"`
	Words         []Word          `json:"words,omitempty"`
	Replacements  []Replacement   `json:"replacements,omitempty"`
	Lexicons      []Lexicon       `json:"lexicons,omitempty"`
	Rulesets      []Ruleset       `json:"rulesets,omitempty"`
	Attachments   json.RawMessage `json:"attachments,omitempty"`
	CreatedAt     time.Time       `json:"created_at,omitempty"`
}

// PackSchemaVersion is the only non-empty schema_version [ValidatePack]
// accepts.
const PackSchemaVersion = "speechkit.customization.pack.v1"

// NormalizeLanguage reduces a locale such as "de-DE" or "en_US" to its
// lowercase two-letter primary language ("de", "en"). Empty, "auto", and
// "multi" mean unspecified and return "", which matches every language.
func NormalizeLanguage(language string) string {
	language = strings.TrimSpace(strings.ToLower(strings.ReplaceAll(language, "_", "-")))
	switch language {
	case "", "auto", "multi":
		// Multilingual / unspecified: do not pin. Slicing "multi" to "mu"
		// used to drop every language-scoped replacement in the default
		// overlay language.
		return ""
	}
	if i := strings.IndexByte(language, '-'); i > 0 {
		language = language[:i]
	}
	if len(language) >= 2 {
		return language[:2]
	}
	return language
}

// NormalizeMode maps mode and its accepted aliases ("dictate",
// "transcribe", "stt", "voice-agent", "realtime_voice", ...) to the
// canonical [Mode]; unknown values return "".
func NormalizeMode(mode Mode) Mode {
	switch strings.TrimSpace(strings.ToLower(string(mode))) {
	case "dictation", "dictate", "transcribe", "stt":
		return ModeDictation
	case "assist":
		return ModeAssist
	case "voice-agent", "voice_agent", "voiceagent", "realtime_voice":
		return ModeVoiceAgent
	default:
		return ""
	}
}

// NormalizeScopeKind trims and lowercases kind and returns the canonical
// [ScopeKind]; "tenant" maps to [ScopeOrg]. Unknown kinds return "".
func NormalizeScopeKind(kind ScopeKind) ScopeKind {
	switch strings.TrimSpace(strings.ToLower(string(kind))) {
	case string(ScopeBuiltin):
		return ScopeBuiltin
	case string(ScopeApp):
		return ScopeApp
	case string(ScopeInstall):
		return ScopeInstall
	case "org", "tenant":
		return ScopeOrg
	case string(ScopeWorkspace):
		return ScopeWorkspace
	case string(ScopeUser):
		return ScopeUser
	case string(ScopeSession):
		return ScopeSession
	default:
		return ""
	}
}

// NormalizeScopeRef canonicalizes ref.Kind with [NormalizeScopeKind] and
// trims ref.Key.
func NormalizeScopeRef(ref ScopeRef) ScopeRef {
	ref.Kind = NormalizeScopeKind(ref.Kind)
	ref.Key = strings.TrimSpace(ref.Key)
	return ref
}

// DefaultDeviceScopeOrder returns the Device host precedence
// builtin < app < install < user < session, lowest first: later layers
// override earlier ones by identity.
func DefaultDeviceScopeOrder() []ScopeRef {
	return []ScopeRef{
		{Kind: ScopeBuiltin},
		{Kind: ScopeApp},
		{Kind: ScopeInstall},
		{Kind: ScopeUser},
		{Kind: ScopeSession},
	}
}

// DefaultServerScopeOrder returns the Server host precedence
// builtin < app < install < org < user < session, lowest first.
func DefaultServerScopeOrder() []ScopeRef {
	return []ScopeRef{
		{Kind: ScopeBuiltin},
		{Kind: ScopeApp},
		{Kind: ScopeInstall},
		{Kind: ScopeOrg},
		{Kind: ScopeUser},
		{Kind: ScopeSession},
	}
}

// NormalizeKind trims and lowercases kind and returns the canonical
// [Kind]; unknown kinds return "".
func NormalizeKind(kind Kind) Kind {
	switch strings.TrimSpace(strings.ToLower(string(kind))) {
	case string(KindSubstitution):
		return KindSubstitution
	case string(KindSynonym):
		return KindSynonym
	case string(KindSnippet):
		return KindSnippet
	case string(KindCommand):
		return KindCommand
	case string(KindTemplate):
		return KindTemplate
	default:
		return ""
	}
}

// NormalizeStage trims and lowercases stage and returns the canonical
// [Stage]; unknown stages return "".
func NormalizeStage(stage Stage) Stage {
	switch strings.TrimSpace(strings.ToLower(string(stage))) {
	case string(StagePreRecognitionCleanup):
		return StagePreRecognitionCleanup
	case string(StagePostSTT):
		return StagePostSTT
	case string(StagePostLLM):
		return StagePostLLM
	case string(StageOutput):
		return StageOutput
	default:
		return ""
	}
}

// NormalizeMatchType trims and lowercases matchType and returns the
// canonical [MatchType]. Empty defaults to [MatchPhrase]; unknown types
// return "".
func NormalizeMatchType(matchType MatchType) MatchType {
	switch strings.TrimSpace(strings.ToLower(string(matchType))) {
	case "", string(MatchPhrase):
		return MatchPhrase
	case string(MatchLiteral):
		return MatchLiteral
	case string(MatchRegex):
		return MatchRegex
	case string(MatchSpokenAlias):
		return MatchSpokenAlias
	default:
		return ""
	}
}

// ValidateWord returns an error when word has a blank Term or a negative
// Weight.
func ValidateWord(word Word) error {
	if strings.TrimSpace(word.Term) == "" {
		return fmt.Errorf("customize: word term is required")
	}
	if word.Weight < 0 {
		return fmt.Errorf("customize: word weight must be >= 0")
	}
	return nil
}

// ValidateReplacement returns an error for the first invalid field of
// replacement: an unknown Kind, Stage, Match.Type, or mode, a blank
// Match.Pattern, or a synonym without Output.Text.
func ValidateReplacement(replacement Replacement) error {
	if NormalizeKind(replacement.Kind) == "" {
		return fmt.Errorf("customize: unsupported replacement kind %q", replacement.Kind)
	}
	if NormalizeStage(replacement.Stage) == "" {
		return fmt.Errorf("customize: unsupported replacement stage %q", replacement.Stage)
	}
	if NormalizeMatchType(replacement.Match.Type) == "" {
		return fmt.Errorf("customize: unsupported match type %q", replacement.Match.Type)
	}
	if strings.TrimSpace(replacement.Match.Pattern) == "" {
		return fmt.Errorf("customize: replacement match pattern is required")
	}
	if replacement.Kind == KindSynonym {
		if strings.TrimSpace(replacement.Output.Text) == "" {
			return fmt.Errorf("customize: replacement output text is required for %s", replacement.Kind)
		}
	}
	for _, mode := range replacement.Modes {
		if NormalizeMode(mode) == "" {
			return fmt.Errorf("customize: unsupported replacement mode %q", mode)
		}
	}
	return nil
}

// ValidatePack validates a pack for import: SchemaVersion must be empty or
// [PackSchemaVersion], every Word and Replacement must pass its validator,
// Lexicons and Rulesets need a Name, and Attachments must be valid JSON
// when present.
func ValidatePack(pack Pack) error {
	if strings.TrimSpace(pack.SchemaVersion) != "" && pack.SchemaVersion != PackSchemaVersion {
		return fmt.Errorf("customize: unsupported pack schema %q", pack.SchemaVersion)
	}
	for _, word := range pack.Words {
		if err := ValidateWord(word); err != nil {
			return err
		}
	}
	for _, replacement := range pack.Replacements {
		if err := ValidateReplacement(replacement); err != nil {
			return err
		}
	}
	for _, lexicon := range pack.Lexicons {
		if strings.TrimSpace(lexicon.Name) == "" {
			return fmt.Errorf("customize: lexicon name is required")
		}
	}
	for _, ruleset := range pack.Rulesets {
		if strings.TrimSpace(ruleset.Name) == "" {
			return fmt.Errorf("customize: ruleset name is required")
		}
	}
	if len(pack.Attachments) > 0 && !json.Valid(pack.Attachments) {
		return fmt.Errorf("customize: pack attachments must be valid JSON")
	}
	return nil
}

// WithDefaultsWord returns word with Term trimmed, Language normalized,
// Source defaulted to "settings", and, when ID is empty, an ID derived
// with [StableID] from language and term.
func WithDefaultsWord(word Word) Word {
	word.Term = strings.TrimSpace(word.Term)
	word.Language = NormalizeLanguage(word.Language)
	word.ID = strings.TrimSpace(word.ID)
	if word.ID == "" {
		word.ID = StableID("word", word.Language, word.Term)
	}
	if strings.TrimSpace(word.Source) == "" {
		word.Source = "settings"
	}
	return word
}

// WithDefaultsReplacement returns replacement with Kind, Stage,
// Match.Type, Match.Pattern, and Language normalized, Source defaulted to
// "settings", and, when ID is empty, an ID derived with [StableID] from
// kind, language, stage, match type, and pattern. Output is not part of
// that identity.
func WithDefaultsReplacement(replacement Replacement) Replacement {
	replacement.ID = strings.TrimSpace(replacement.ID)
	replacement.Kind = NormalizeKind(replacement.Kind)
	replacement.Stage = NormalizeStage(replacement.Stage)
	replacement.Match.Type = NormalizeMatchType(replacement.Match.Type)
	replacement.Match.Pattern = strings.TrimSpace(replacement.Match.Pattern)
	replacement.Language = NormalizeLanguage(replacement.Language)
	if strings.TrimSpace(replacement.Source) == "" {
		replacement.Source = "settings"
	}
	if replacement.ID == "" {
		replacement.ID = StableID("replacement", string(replacement.Kind), replacement.Language, string(replacement.Stage), string(replacement.Match.Type), replacement.Match.Pattern)
	}
	return replacement
}

// StableID derives a deterministic "<prefix>_<16 hex chars>" identifier
// from a SHA-256 over the trimmed, lowercased parts, so equal authoring
// identities always map to the same ID.
func StableID(prefix string, parts ...string) string {
	h := sha256.New()
	for _, part := range parts {
		_, _ = h.Write([]byte(strings.ToLower(strings.TrimSpace(part))))
		_, _ = h.Write([]byte{0})
	}
	return strings.TrimSpace(prefix) + "_" + hex.EncodeToString(h.Sum(nil))[:16]
}
