export { SpeechKitClient, type ClientOptions, type RequestOverrides } from "./client.js";
export {
  HTTPError,
  type AudioAsset,
  type CatalogReadiness,
  type DiarizationResult,
  type DictionaryEntry,
  type ModelVariant,
  type ModeContract,
  type ProviderProfile,
  type RecognitionHints,
  type ReadinessAction,
  type ReadinessArtifact,
  type ReadinessRequirement,
  type Speaker,
  type SpeakerSegment,
  type SpeakerWord,
  type Status,
  type TTSSynthesizeRequest,
  type TTSSynthesizeResponse,
  type Transcript,
  type TranscribeOptions,
  type TranscribeResponse,
  type Voice,
  type VoiceAgentSessionSummary,
  type VoiceAgentSessionTicket,
  type VoiceAgentTurn,
  type VoiceAgentSummary,
  type VoiceAgentTranscript,
} from "./types.js";
export type { components, operations, paths } from "./generated/openapi.js";
