ALTER TABLE recording_session_enhancements
    ADD COLUMN IF NOT EXISTS stage TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS progress INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS attempt INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS input_fingerprint TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS error_kind TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS retryable BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS consent_version INTEGER NOT NULL DEFAULT 0;
