package catalog

import (
	"sort"

	"github.com/kombifyio/SpeechKit/pkg/speechkit"
)

const DefaultLocalBuiltInLLMModel = "ggml-org/gemma-4-E2B-it-GGUF:Q8_0"

// DefaultProviderProfiles returns the built-in framework provider catalog for
// the three strict SpeechKit modes. The Windows desktop host adapts this
// public catalog into its internal runtime model; the catalog itself belongs to
// the reusable framework layer.
func DefaultProviderProfiles() []speechkit.ProviderProfile {
	profiles := []speechkit.ProviderProfile{
		{
			ID:            "stt.local.whispercpp",
			Mode:          speechkit.ModeDictation,
			Name:          "Whisper.cpp (Local Built-in)",
			ProviderKind:  speechkit.ProviderKindLocalBuiltIn,
			ExecutionMode: speechkit.ExecutionModeLocal,
			ModelID:       "whisper.cpp",
			Source:        "Local Built-in",
			Description:   "SpeechKit-managed local runtime for Transcribe. Download options provide the concrete Whisper-compatible transcription models.",
			License:       "mit",
			Capabilities:  []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryPrompt},
			AdapterKind:   "stt_router",
			Variants: []speechkit.ModelVariant{
				{ID: "whisper.ggml-small", Name: "Whisper Small Multilingual", ModelID: "ggml-small.bin"},
				{ID: "whisper.ggml-large-v3-turbo", Name: "Whisper Large v3 Turbo", ModelID: "ggml-large-v3-turbo.bin", Recommended: true},
				{ID: "whisper.ggml-large-v3", Name: "Whisper Large v3", ModelID: "ggml-large-v3.bin"},
			},
			AllowInference: false,
			Default:        true,
			Recommended:    true,
		},
		{
			ID:             "stt.ollama.gemma4-e4b-transcribe",
			Mode:           speechkit.ModeDictation,
			Name:           "Gemma 4 E4B Transcribe (Ollama)",
			ProviderKind:   speechkit.ProviderKindLocalProvider,
			ExecutionMode:  speechkit.ExecutionModeOllama,
			ModelID:        "gemma4:e4b",
			Source:         "Local Provider",
			Description:    "User-managed Ollama provider through SpeechKit's constrained Dictation adapter. Audio in, transcription text out.",
			License:        "gemma",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryPrompt},
			AdapterKind:    "ollama_transcription",
			AllowInference: true,
			Experimental:   true,
		},
		{
			ID:             "stt.routed.whisper-large-v3",
			Mode:           speechkit.ModeDictation,
			Name:           "Whisper Large v3 Turbo (Hugging Face)",
			ProviderKind:   speechkit.ProviderKindCloudProvider,
			ExecutionMode:  speechkit.ExecutionModeHFRouted,
			ModelID:        "openai/whisper-large-v3-turbo",
			Source:         "Hugging Face",
			Description:    "Fast multilingual transcription over the Hugging Face Inference Router. Requires an HF token.",
			License:        "mit",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryPrompt},
			AdapterKind:    "stt_router",
			AllowInference: true,
			Recommended:    true,
		},
		{
			ID:             "stt.openrouter.whisper-1",
			Mode:           speechkit.ModeDictation,
			Name:           "Whisper-1 (OpenRouter)",
			ProviderKind:   speechkit.ProviderKindCloudProvider,
			ExecutionMode:  speechkit.ExecutionModeOpenRouter,
			ModelID:        "openai/whisper-1",
			Source:         "OpenRouter",
			Description:    "Gateway-routed transcription through OpenRouter's speech-to-text endpoint.",
			License:        "apache-2.0",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryPrompt},
			AdapterKind:    "openrouter_stt",
			AllowInference: true,
		},
		{
			ID:            "stt.openai.gpt-4o-transcribe",
			Mode:          speechkit.ModeDictation,
			Name:          "GPT-4o Transcribe (OpenAI)",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeOpenAI,
			ModelID:       ModelOpenAIGPT4OTranscribe,
			Lifecycle:     speechkit.ModelLifecycleGA,
			Source:        "OpenAI",
			Description:   "Current OpenAI direct transcription profile for long dictation and meeting audio when an OpenAI API key is configured. Speaker diarization is kept out of this profile until the adapter maps diarized_json segments.",
			License:       "proprietary",
			Capabilities:  []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryPrompt},
			AdapterKind:   "stt_router",
			EvidenceURL:   "https://platform.openai.com/docs/guides/speech-to-text",
			Variants: []speechkit.ModelVariant{
				{ID: "openai.gpt-4o-transcribe", Name: "GPT-4o Transcribe", ModelID: ModelOpenAIGPT4OTranscribe, Recommended: true},
				{ID: "openai.gpt-4o-mini-transcribe", Name: "GPT-4o mini Transcribe", ModelID: ModelOpenAIGPT4OMiniTranscribe},
				{ID: "openai.gpt-4o-transcribe-diarize", Name: "GPT-4o Transcribe Diarize", ModelID: ModelOpenAIGPT4OTranscribeDiarize, Description: "Catalog-only variant until SpeechKit maps diarized_json speaker segments."},
				{ID: "openai.whisper-1", Name: "Whisper-1", ModelID: "whisper-1", Description: "Legacy fallback for older OpenAI-compatible deployments."},
			},
			AllowInference: true,
			Default:        true,
			Recommended:    true,
		},
		{
			ID:             "stt.openai.whisper-1",
			Mode:           speechkit.ModeDictation,
			Name:           "Whisper-1 (OpenAI)",
			ProviderKind:   speechkit.ProviderKindDirectProvider,
			ExecutionMode:  speechkit.ExecutionModeOpenAI,
			ModelID:        "whisper-1",
			Lifecycle:      speechkit.ModelLifecycleLegacy,
			Source:         "OpenAI",
			Description:    "Legacy direct transcription fallback for older deployments that still pin OpenAI whisper-1.",
			License:        "apache-2.0",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryPrompt},
			AdapterKind:    "stt_router",
			EvidenceURL:    "https://platform.openai.com/docs/guides/speech-to-text",
			AllowInference: true,
		},
		{
			ID:            "stt.foundry.gpt-4o-mini-transcribe",
			Mode:          speechkit.ModeDictation,
			Name:          "GPT-4o mini Transcribe (Microsoft Foundry)",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeFoundry,
			Provider:      "foundry",
			ModelID:       "gpt-4o-mini-transcribe",
			Lifecycle:     speechkit.ModelLifecycleGA,
			Source:        "Microsoft Foundry",
			Description:   "Azure-hosted transcription through the Microsoft Foundry OpenAI-compatible v1 surface. The model id is the default deployment name — override it with your own deployment name in the Foundry integration settings.",
			License:       "proprietary",
			Capabilities:  []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryPrompt},
			AdapterKind:   "stt_router",
			EvidenceURL:   "https://learn.microsoft.com/azure/ai-foundry/openai/reference",
			Variants: []speechkit.ModelVariant{
				{ID: "foundry.gpt-4o-mini-transcribe", Name: "GPT-4o mini Transcribe", ModelID: "gpt-4o-mini-transcribe", Recommended: true},
				{ID: "foundry.gpt-4o-transcribe", Name: "GPT-4o Transcribe", ModelID: "gpt-4o-transcribe"},
				{ID: "foundry.whisper", Name: "Whisper", ModelID: "whisper", Description: "Azure OpenAI whisper deployment for legacy setups."},
			},
			AllowInference: true,
			Recommended:    true,
		},
		{
			// MAI-Transcribe is served by the Azure Speech surface of the same
			// Foundry resource (fast transcription with enhancedMode), not by
			// a deployment. The model id is sent verbatim; no deployment
			// exists to rename.
			ID:            "stt.foundry.mai-transcribe-2",
			Mode:          speechkit.ModeDictation,
			Name:          "MAI-Transcribe-2 (Microsoft Foundry)",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeFoundry,
			Provider:      "foundry",
			ModelID:       "MAI-Transcribe-2",
			Lifecycle:     speechkit.ModelLifecyclePreview,
			Source:        "Microsoft Foundry",
			Description:   "Microsoft's own speech recognition model through Azure Speech fast transcription on the Foundry resource: 60 languages with automatic language detection, speaker diarization, clean or verbatim transcripts and phrase biasing from Words & Replacements. Public preview.",
			License:       "proprietary",
			Capabilities:  []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryPrompt},
			AdapterKind:   "stt_router",
			EvidenceURL:   "https://learn.microsoft.com/azure/ai-services/speech-service/mai-transcribe",
			Variants: []speechkit.ModelVariant{
				{ID: "foundry.mai-transcribe-2", Name: "MAI-Transcribe-2 (Preview)", ModelID: "MAI-Transcribe-2", Recommended: true},
				{ID: "foundry.mai-transcribe-1.5", Name: "MAI-Transcribe-1.5 (Preview)", ModelID: "MAI-Transcribe-1.5", Description: "Previous generation; fewer languages."},
			},
			AllowInference: true,
			Recommended:    true,
			Experimental:   true,
		},
		{
			ID:             "stt.google.latest-long",
			Mode:           speechkit.ModeDictation,
			Name:           "Latest Long (Google STT)",
			ProviderKind:   speechkit.ProviderKindDirectProvider,
			ExecutionMode:  speechkit.ExecutionModeGoogle,
			ModelID:        "latest_long",
			Source:         "Google Cloud Speech-to-Text",
			Description:    "Google-hosted transcription path. Requires a dedicated Google STT key; Gemini's GOOGLE_AI_API_KEY does not enable this profile by itself.",
			License:        "proprietary",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryNativeHints, speechkit.CapabilitySpeakerDiarization},
			AdapterKind:    "stt_router",
			AllowInference: true,
		},
		{
			ID:             "stt.google.latest-long-diarization",
			Mode:           speechkit.ModeDictation,
			Name:           "Latest Long Diarization (Google STT)",
			ProviderKind:   speechkit.ProviderKindDirectProvider,
			ExecutionMode:  speechkit.ExecutionModeGoogle,
			ModelID:        "latest_long",
			Source:         "Google Cloud Speech-to-Text",
			Description:    "Google-hosted transcription with optional word-level speaker diarization. Requires SPEECHKIT_GOOGLE_STT_API_KEY; GOOGLE_AI_API_KEY is not enough for this STT profile.",
			License:        "proprietary",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryNativeHints, speechkit.CapabilitySpeakerDiarization},
			AdapterKind:    "stt_router",
			AllowInference: true,
		},
		{
			ID:             "stt.deepgram.nova-3",
			Mode:           speechkit.ModeDictation,
			Name:           "Nova-3 (Deepgram)",
			ProviderKind:   speechkit.ProviderKindDirectProvider,
			ExecutionMode:  speechkit.ExecutionModeDeepgram,
			ModelID:        "nova-3",
			Source:         "Deepgram",
			Description:    "Deepgram-hosted Nova-3 transcription. Low-latency streaming + batch STT; the recommended first-level cloud transcription path for kombify reference deployments.",
			License:        "proprietary",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryPrompt, speechkit.CapabilityNativeDictationStream},
			AdapterKind:    "deepgram_stt",
			AllowInference: true,
			Recommended:    true,
		},
		{
			ID:             "stt.deepgram.nova-3-diarization",
			Mode:           speechkit.ModeDictation,
			Name:           "Nova-3 Diarization (Deepgram)",
			ProviderKind:   speechkit.ProviderKindDirectProvider,
			ExecutionMode:  speechkit.ExecutionModeDeepgram,
			ModelID:        "nova-3",
			Source:         "Deepgram",
			Description:    "Deepgram-hosted transcription with diarize_model=latest for batch speaker labels and word-level speaker confidence.",
			License:        "proprietary",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilitySpeakerDiarization},
			AdapterKind:    "deepgram_stt",
			AllowInference: true,
			Recommended:    true,
		},
		{
			ID:             "stt.assemblyai.universal",
			Mode:           speechkit.ModeDictation,
			Name:           "Universal-3.5 Pro (AssemblyAI)",
			ProviderKind:   speechkit.ProviderKindDirectProvider,
			ExecutionMode:  speechkit.ExecutionModeAssemblyAI,
			ModelID:        "universal-3-5-pro,universal-2",
			Source:         "AssemblyAI",
			Description:    "AssemblyAI Universal-3.5 Pro. Short clips ride the synchronous endpoint (finished transcript in one request, ~134 ms p50) with prompt steering, keyterms, and conversation context; longer or feature-rich requests use the async flow, and realtime dictation streams over v3 with agent context. The diarization variant adds speaker labels and content-based speaker identification by name/role.",
			License:        "proprietary",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryPrompt, speechkit.CapabilityNativeContextPrompt, speechkit.CapabilityNativeDictationStream},
			AdapterKind:    "assemblyai_stt",
			AllowInference: true,
			Recommended:    true,
		},
		{
			ID:             "stt.assemblyai.universal-diarization",
			Mode:           speechkit.ModeDictation,
			Name:           "Universal-3.5 Pro Diarization + Speaker Identification (AssemblyAI)",
			ProviderKind:   speechkit.ProviderKindDirectProvider,
			ExecutionMode:  speechkit.ExecutionModeAssemblyAI,
			ModelID:        "universal-3-5-pro,universal-2",
			Source:         "AssemblyAI",
			Description:    "AssemblyAI pre-recorded transcription with speaker_labels and optional content-based speaker identification by known names or roles. Diarization requests always use the async flow (the sync endpoint does not diarize).",
			License:        "proprietary",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilitySpeakerDiarization, speechkit.CapabilitySpeakerIdentification, speechkit.CapabilitySpeakerAttribution},
			AdapterKind:    "assemblyai_stt",
			AllowInference: true,
			Recommended:    true,
		},
		{
			ID:            "stt.groq.whisper-large-v3-turbo",
			Mode:          speechkit.ModeDictation,
			Name:          "Whisper Large v3 Turbo (Groq)",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeGroq,
			ModelID:       ModelGroqWhisperLargeV3Turbo,
			Source:        "Groq",
			Description:   "Fast direct API transcription profile for low-latency dictation fallbacks.",
			License:       "proprietary",
			Capabilities:  []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryPrompt},
			AdapterKind:   "stt_router",
			EvidenceURL:   "https://console.groq.com/docs/speech-to-text",
			Variants: []speechkit.ModelVariant{
				{ID: "groq.whisper-large-v3-turbo", Name: "Whisper Large v3 Turbo", ModelID: ModelGroqWhisperLargeV3Turbo, Recommended: true},
				{ID: "groq.whisper-large-v3", Name: "Whisper Large v3", ModelID: ModelGroqWhisperLargeV3, Description: "Higher-accuracy Groq STT option for hosts that prefer quality over the turbo profile."},
			},
			AllowInference: true,
			Recommended:    true,
		},
		{
			ID:            "assist.builtin.gemma4-e4b",
			Mode:          speechkit.ModeAssist,
			Name:          "Gemma 4 E4B (Local Built-in)",
			ProviderKind:  speechkit.ProviderKindLocalBuiltIn,
			ExecutionMode: speechkit.ExecutionModeLocal,
			ModelID:       DefaultLocalBuiltInLLMModel,
			Source:        "Local Built-in",
			Description:   "SpeechKit-managed llama.cpp runtime for Assist. Download options provide concrete GGUF model files.",
			License:       "gemma",
			Capabilities:  []speechkit.Capability{speechkit.CapabilityLLM, speechkit.CapabilityToolCalling, speechkit.CapabilitySessionSummary},
			AdapterKind:   "genkit_llm",
			Variants: []speechkit.ModelVariant{
				{ID: "llamacpp.gemma-4-e2b-it-q8-0", Name: "Gemma 4 E2B IT Q8_0", ModelID: "gemma-4-E2B-it-Q8_0.gguf", Description: "Default lightweight GGUF model for local Assist usage.", Recommended: true},
				{ID: "llamacpp.gemma-4-e4b-it-q4-k-m", Name: "Gemma 4 E4B IT Q4_K_M", ModelID: "gemma-4-E4B-it-Q4_K_M.gguf", Description: "Stronger optional GGUF model for devices with enough memory."},
			},
			AllowInference: true,
			Default:        true,
			Recommended:    true,
		},
		{
			ID:             "assist.ollama.gemma4-e4b",
			Mode:           speechkit.ModeAssist,
			Name:           "Gemma 4 E4B (Ollama)",
			ProviderKind:   speechkit.ProviderKindLocalProvider,
			ExecutionMode:  speechkit.ExecutionModeOllama,
			ModelID:        "gemma4:e4b",
			Source:         "Local Provider",
			Description:    "Externally managed Ollama provider for Assist Mode.",
			License:        "gemma",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityLLM, speechkit.CapabilityToolCalling, speechkit.CapabilitySessionSummary},
			AdapterKind:    "genkit_llm",
			AllowInference: true,
			Recommended:    true,
		},
		{
			ID:             "assist.routed.qwen35-27b",
			Mode:           speechkit.ModeAssist,
			Name:           "Qwen 3.5 27B (Hugging Face)",
			ProviderKind:   speechkit.ProviderKindCloudProvider,
			ExecutionMode:  speechkit.ExecutionModeHFRouted,
			ModelID:        "Qwen/Qwen3.5-27B",
			Source:         "Hugging Face",
			Description:    "Strong open-weight Assist model over Hugging Face.",
			License:        "apache-2.0",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityLLM, speechkit.CapabilityToolCalling, speechkit.CapabilitySessionSummary},
			AdapterKind:    "genkit_llm",
			AllowInference: true,
			Recommended:    true,
		},
		{
			ID:             "assist.openai.gpt-5.4",
			Mode:           speechkit.ModeAssist,
			Name:           "GPT-5.4 (OpenAI)",
			ProviderKind:   speechkit.ProviderKindDirectProvider,
			ExecutionMode:  speechkit.ExecutionModeOpenAI,
			ModelID:        "gpt-5.4-2026-03-05",
			Source:         "OpenAI",
			Description:    "Frontier hosted LLM for the Assist tier.",
			License:        "proprietary",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityLLM, speechkit.CapabilityToolCalling, speechkit.CapabilitySessionSummary},
			AdapterKind:    "genkit_llm",
			AllowInference: true,
			Recommended:    true,
		},
		{
			ID:            "assist.foundry.gpt-5.1",
			Mode:          speechkit.ModeAssist,
			Name:          "GPT-5.1 (Microsoft Foundry)",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeFoundry,
			Provider:      "foundry",
			ModelID:       "gpt-5.1",
			Source:        "Microsoft Foundry",
			Description:   "Azure-hosted frontier LLM for Assist and meeting summaries via the Microsoft Foundry OpenAI-compatible v1 surface. The model id is the default deployment name — override it with your own deployment name in the Foundry integration settings.",
			License:       "proprietary",
			Capabilities:  []speechkit.Capability{speechkit.CapabilityLLM, speechkit.CapabilityToolCalling, speechkit.CapabilitySessionSummary},
			AdapterKind:   "genkit_llm",
			EvidenceURL:   "https://learn.microsoft.com/azure/ai-foundry/openai/reference",
			Variants: []speechkit.ModelVariant{
				{ID: "foundry.gpt-5.1", Name: "GPT-5.1", ModelID: "gpt-5.1", Recommended: true},
				{ID: "foundry.gpt-5.2", Name: "GPT-5.2", ModelID: "gpt-5.2"},
				{ID: "foundry.gpt-5-mini", Name: "GPT-5 mini", ModelID: "gpt-5-mini"},
				{ID: "foundry.gpt-5-nano", Name: "GPT-5 nano", ModelID: "gpt-5-nano"},
				// Microsoft-publisher deployment; served on /mai/v1 rather than
				// /openai/v1, text only, and quota starts at zero until requested.
				{ID: "foundry.mai-thinking-1", Name: "MAI-Thinking-1 (Preview)", ModelID: "MAI-Thinking-1", Description: "Microsoft's reasoning model (256k context, 64k output). Needs a MAI-Thinking-1 deployment plus a quota request in the Foundry project; text only."},
			},
			AllowInference: true,
			Recommended:    true,
		},
		{
			ID:             "assist.google.gemini-2.5-flash",
			Mode:           speechkit.ModeAssist,
			Name:           "Gemini 2.5 Flash (Google AI)",
			ProviderKind:   speechkit.ProviderKindDirectProvider,
			ExecutionMode:  speechkit.ExecutionModeGoogle,
			ModelID:        "gemini-2.5-flash",
			Source:         "Google AI",
			Description:    "Direct Gemini Assist profile for users who enable Google AI for Voice Agent or Assist.",
			License:        "proprietary",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityLLM, speechkit.CapabilityToolCalling, speechkit.CapabilitySessionSummary},
			AdapterKind:    "genkit_llm",
			AllowInference: true,
		},
		{
			ID:             "assist.openrouter.gemini-2.5-flash",
			Mode:           speechkit.ModeAssist,
			Name:           "Gemini 2.5 Flash (OpenRouter)",
			ProviderKind:   speechkit.ProviderKindCloudProvider,
			ExecutionMode:  speechkit.ExecutionModeOpenRouter,
			ModelID:        "google/gemini-2.5-flash",
			Source:         "OpenRouter",
			Description:    "Gateway-routed Assist profile. OpenRouter is shown as a cloud router, not a direct provider.",
			License:        "proprietary",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityLLM, speechkit.CapabilityToolCalling, speechkit.CapabilitySessionSummary},
			AdapterKind:    "genkit_llm",
			AllowInference: true,
		},
		{
			ID:             "assist.groq.llama-3.3-70b",
			Mode:           speechkit.ModeAssist,
			Name:           "Llama 3.3 70B (Groq)",
			ProviderKind:   speechkit.ProviderKindDirectProvider,
			ExecutionMode:  speechkit.ExecutionModeGroq,
			ModelID:        "llama-3.3-70b-versatile",
			Source:         "Groq",
			Description:    "Groq-hosted Assist profile for fast one-shot responses.",
			License:        "llama",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityLLM, speechkit.CapabilityToolCalling, speechkit.CapabilitySessionSummary},
			AdapterKind:    "genkit_llm",
			AllowInference: true,
		},
		{
			ID:            "realtime.builtin.pipeline",
			Mode:          speechkit.ModeVoiceAgent,
			Name:          "SpeechKit Local Voice Pipeline",
			ProviderKind:  speechkit.ProviderKindLocalBuiltIn,
			ExecutionMode: speechkit.ExecutionModeLocal,
			ModelID:       "speechkit-local-voice-pipeline",
			Source:        "Local Built-in",
			Description:   "Voice Agent pipeline fallback using local transcription, SpeechKit-managed llama.cpp dialogue, and a TTS path.",
			License:       "mixed",
			Capabilities:  []speechkit.Capability{speechkit.CapabilityAudioInput, speechkit.CapabilityPipelineFallback, speechkit.CapabilitySessionSummary},
			AdapterKind:   "voice_pipeline",
			Variants: []speechkit.ModelVariant{
				{ID: "llamacpp.gemma-4-e2b-it-q8-0-voice", Name: "Gemma 4 E2B IT Q8_0", ModelID: "gemma-4-E2B-it-Q8_0.gguf", Description: "Default lightweight GGUF model for local Voice Agent pipeline fallback.", Recommended: true},
				{ID: "llamacpp.gemma-4-e4b-it-q4-k-m-voice", Name: "Gemma 4 E4B IT Q4_K_M", ModelID: "gemma-4-E4B-it-Q4_K_M.gguf", Description: "Stronger optional GGUF model for Voice Agent pipeline fallback."},
			},
			AllowInference: true,
			Default:        true,
			Recommended:    true,
			Experimental:   true,
		},
		{
			ID:             "realtime.ollama.gemma4-e4b-pipeline",
			Mode:           speechkit.ModeVoiceAgent,
			Name:           "Gemma 4 E4B Voice Pipeline (Ollama)",
			ProviderKind:   speechkit.ProviderKindLocalProvider,
			ExecutionMode:  speechkit.ExecutionModeOllama,
			ModelID:        "gemma4:e4b",
			Source:         "Local Provider",
			Description:    "Voice Agent pipeline fallback with Ollama as the dialogue model.",
			License:        "gemma",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityAudioInput, speechkit.CapabilityPipelineFallback, speechkit.CapabilitySessionSummary},
			AdapterKind:    "voice_pipeline",
			AllowInference: true,
			Experimental:   true,
		},
		{
			ID:             "realtime.hf.qwen35-27b",
			Mode:           speechkit.ModeVoiceAgent,
			Name:           "Qwen 3.5 27B Voice Fallback (Hugging Face)",
			ProviderKind:   speechkit.ProviderKindCloudProvider,
			ExecutionMode:  speechkit.ExecutionModeHFRouted,
			ModelID:        "Qwen/Qwen3.5-27B",
			Source:         "Hugging Face",
			Description:    "Voice Agent fallback over Hugging Face. SpeechKit uses the capture pipeline when Gemini Live is unavailable or not selected.",
			License:        "apache-2.0",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityAudioInput, speechkit.CapabilityPipelineFallback, speechkit.CapabilitySessionSummary},
			AdapterKind:    "voice_pipeline",
			AllowInference: true,
			Recommended:    true,
			Experimental:   true,
		},
		{
			ID:             "realtime.openrouter.gemini-2.5-flash-pipeline",
			Mode:           speechkit.ModeVoiceAgent,
			Name:           "Gemini 2.5 Flash Voice Pipeline (OpenRouter)",
			ProviderKind:   speechkit.ProviderKindCloudProvider,
			ExecutionMode:  speechkit.ExecutionModeOpenRouter,
			ModelID:        "google/gemini-2.5-flash",
			Source:         "OpenRouter",
			Description:    "Voice Agent pipeline fallback with OpenRouter as the dialogue model.",
			License:        "proprietary",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityAudioInput, speechkit.CapabilityPipelineFallback, speechkit.CapabilitySessionSummary},
			AdapterKind:    "voice_pipeline",
			AllowInference: true,
			Experimental:   true,
		},
		{
			ID:            "realtime.google.gemini-native-audio",
			Mode:          speechkit.ModeVoiceAgent,
			Name:          "Gemini Live Native Audio",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeGoogle,
			Provider:      "google",
			ModelID:       ModelGemini31FlashLivePreview,
			Lifecycle:     speechkit.ModelLifecyclePreview,
			Source:        "Google",
			Description:   "Native real-time voice conversation over the Google Live API. Gemini 3.1 Flash Live is the primary preview; Gemini 2.5 Flash Native Audio remains the same-provider fallback.",
			License:       "proprietary",
			Capabilities: []speechkit.Capability{
				speechkit.CapabilityAudioInput,
				speechkit.CapabilityRealtimeAudio,
				speechkit.CapabilityToolCalling,
				speechkit.CapabilityNativeContextPrompt,
				speechkit.CapabilityReasoningEffort,
				speechkit.CapabilitySessionResume,
				speechkit.CapabilityTranscript,
				speechkit.CapabilityInterruptions,
				speechkit.CapabilitySessionSummary,
			},
			SupportedLocales: []string{"*"},
			NativeOptions:    []string{"context_prompt", "reasoning_effort"},
			AuthRequirement:  "api_key",
			Transport:        "websocket",
			EvidenceURL:      "https://ai.google.dev/gemini-api/docs/live-guide",
			AdapterKind:      "gemini_live",
			Variants: []speechkit.ModelVariant{
				{ID: "gemini.3.1.flash-live-preview", Name: "Gemini 3.1 Flash Live Preview", ModelID: ModelGemini31FlashLivePreview, Recommended: true},
				{ID: "gemini.2.5.flash-native-audio-preview", Name: "Gemini 2.5 Flash Native Audio Preview", ModelID: ModelGemini25FlashNativeAudioPreview},
			},
			AllowInference: true,
			Recommended:    true,
		},
		{
			ID:            "realtime.google.gemini-live-translate",
			Mode:          speechkit.ModeVoiceAgent,
			Name:          "Gemini 3.5 Live Translate",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeGoogle,
			Provider:      "google",
			ModelID:       ModelGemini35LiveTranslatePreview,
			Lifecycle:     speechkit.ModelLifecyclePreview,
			Source:        "Google",
			Description:   "Specialized Live API speech-to-speech translation profile. It is deliberately separate from the general Gemini Live dialogue profile so Voice Agent defaults do not point at a translation-only model.",
			License:       "proprietary",
			Capabilities: []speechkit.Capability{
				speechkit.CapabilityAudioInput,
				speechkit.CapabilityRealtimeAudio,
				speechkit.CapabilityTranslation,
				speechkit.CapabilityTranscript,
				speechkit.CapabilityInterruptions,
				speechkit.CapabilitySessionSummary,
			},
			SupportedLocales: []string{"*"},
			NativeOptions:    []string{"translation", "turn_detection"},
			AuthRequirement:  "api_key",
			Transport:        "websocket",
			EvidenceURL:      "https://ai.google.dev/gemini-api/docs/models/gemini-3.5-live-translate-preview",
			AdapterKind:      "gemini_live_translate",
			Variants: []speechkit.ModelVariant{
				{ID: "gemini.3.5.live-translate-preview", Name: "Gemini 3.5 Live Translate Preview", ModelID: ModelGemini35LiveTranslatePreview, Recommended: true},
			},
			AllowInference: true,
			Recommended:    true,
			Experimental:   true,
		},
		{
			ID:            "realtime.deepgram.voice-agent",
			Mode:          speechkit.ModeVoiceAgent,
			Name:          "Deepgram Voice Agent (Flux)",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeDeepgram,
			Provider:      "deepgram",
			ModelID:       ModelDeepgramFluxGeneralMulti + "+aura-2",
			Lifecycle:     speechkit.ModelLifecycleGA,
			Source:        "Deepgram",
			Description:   "Deepgram Voice Agent API — native audio-to-audio dialogue (Flux listen with turn events, configurable think LLM, Aura-2 speak) over a single WebSocket. Flux TTS is selectable for English-pinned sessions. Nova-3 remains the general dictation/diarization baseline.",
			License:       "proprietary",
			Capabilities: []speechkit.Capability{
				speechkit.CapabilityAudioInput,
				speechkit.CapabilityRealtimeAudio,
				speechkit.CapabilityToolCalling,
				speechkit.CapabilityWordsNativeHints,
				speechkit.CapabilityNativeContextPrompt,
				speechkit.CapabilityNativeKeyterms,
				speechkit.CapabilityLanguageHints,
				speechkit.CapabilitySpeakerStreaming,
				speechkit.CapabilityTranscript,
				speechkit.CapabilityInterruptions,
				speechkit.CapabilitySessionSummary,
			},
			SupportedLocales: []string{"en", "de", "es", "fr", "hi", "it", "ja", "nl", "pt", "ru"},
			NativeOptions:    []string{"context_prompt", "language_hints", "keyterms", "turn_detection"},
			AuthRequirement:  "api_key",
			Transport:        "websocket",
			EvidenceURL:      "https://developers.deepgram.com/docs/voice-agent-settings",
			AdapterKind:      "deepgram_voice_agent",
			Variants: []speechkit.ModelVariant{
				{ID: "deepgram.flux-general-multi", Name: "Flux General Multilingual", ModelID: ModelDeepgramFluxGeneralMulti, Recommended: true},
				{ID: "deepgram.flux-general-en", Name: "Flux General English", ModelID: ModelDeepgramFluxGeneralEN},
				{ID: "deepgram.flux-general-en-flux-tts", Name: "Flux General English + Flux TTS", ModelID: ModelDeepgramFluxGeneralEN + "+" + ModelDeepgramFluxTTSDefaultEN},
				{ID: "deepgram.nova-3-legacy-agent-listen", Name: "Nova-3 Listen (legacy)", ModelID: ModelDeepgramNova3},
			},
			AllowInference: true,
			Recommended:    true,
		},
		{
			ID:            "realtime.assemblyai.voice-agent",
			Mode:          speechkit.ModeVoiceAgent,
			Name:          "AssemblyAI Voice Agent",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeAssemblyAI,
			Provider:      "assemblyai",
			ModelID:       ModelAssemblyAIVoiceAgent,
			Lifecycle:     speechkit.ModelLifecycleGA,
			Source:        "AssemblyAI",
			Description:   "AssemblyAI Voice Agent API over wss://agents.assemblyai.com/v1/ws with native session.update, session.ready, input.audio, reply.audio, transcripts, tools, and clean session.end teardown.",
			License:       "proprietary",
			Capabilities: []speechkit.Capability{
				speechkit.CapabilityAudioInput,
				speechkit.CapabilityRealtimeAudio,
				speechkit.CapabilityToolCalling,
				speechkit.CapabilityWordsNativeHints,
				speechkit.CapabilityNativeContextPrompt,
				speechkit.CapabilityNativeKeyterms,
				speechkit.CapabilitySessionResume,
				speechkit.CapabilitySpeakerStreaming,
				speechkit.CapabilityTranscript,
				speechkit.CapabilityInterruptions,
				speechkit.CapabilitySessionSummary,
			},
			SupportedLocales: []string{"en", "es", "de", "fr", "pt", "it", "tr", "nl", "sv", "no", "da", "fi", "hi", "vi", "ar", "he", "ja", "zh"},
			NativeOptions:    []string{"context_prompt", "keyterms", "resume"},
			AuthRequirement:  "api_key",
			Transport:        "websocket",
			EvidenceURL:      "https://www.assemblyai.com/docs/voice-agents/voice-agent-api",
			AdapterKind:      "assemblyai_voice_agent",
			AllowInference:   true,
			Recommended:      true,
		},
		{
			ID:            "realtime.openai.gpt-realtime-2",
			Mode:          speechkit.ModeVoiceAgent,
			Name:          "OpenAI Realtime",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeOpenAI,
			Provider:      "openai",
			ModelID:       ModelOpenAIRealtime2,
			Lifecycle:     speechkit.ModelLifecycleGA,
			Source:        "OpenAI",
			Description:   "OpenAI Realtime native audio session for apps that want the same LiveProvider contract with OpenAI's realtime model.",
			License:       "proprietary",
			Capabilities: []speechkit.Capability{
				speechkit.CapabilityAudioInput,
				speechkit.CapabilityRealtimeAudio,
				speechkit.CapabilityToolCalling,
				speechkit.CapabilityNativeContextPrompt,
				speechkit.CapabilityReasoningEffort,
				speechkit.CapabilityTranslation,
				speechkit.CapabilityTranscriptionOnly,
				speechkit.CapabilityTranscript,
				speechkit.CapabilityInterruptions,
				speechkit.CapabilitySessionSummary,
			},
			SupportedLocales: []string{"*"},
			NativeOptions:    []string{"context_prompt", "reasoning_effort", "turn_detection", "transcription_only", "translation"},
			AuthRequirement:  "api_key",
			Transport:        "websocket",
			EvidenceURL:      "https://platform.openai.com/docs/guides/realtime",
			AdapterKind:      "openai_realtime",
			AllowInference:   true,
			Recommended:      true,
		},
		{
			ID:            "realtime.foundry.gpt-realtime-2",
			Mode:          speechkit.ModeVoiceAgent,
			Name:          "Microsoft Foundry Realtime",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeFoundry,
			Provider:      "foundry",
			ModelID:       ModelOpenAIRealtime2,
			Lifecycle:     speechkit.ModelLifecycleGA,
			Source:        "Microsoft Foundry",
			Description:   "Azure-hosted OpenAI Realtime session over the Microsoft Foundry v1 websocket surface. The model id is the default deployment name — override it with your own deployment name in the Foundry integration settings.",
			License:       "proprietary",
			Capabilities: []speechkit.Capability{
				speechkit.CapabilityAudioInput,
				speechkit.CapabilityRealtimeAudio,
				speechkit.CapabilityToolCalling,
				speechkit.CapabilityNativeContextPrompt,
				speechkit.CapabilityReasoningEffort,
				speechkit.CapabilityTranslation,
				speechkit.CapabilityTranscriptionOnly,
				speechkit.CapabilityTranscript,
				speechkit.CapabilityInterruptions,
				speechkit.CapabilitySessionSummary,
			},
			SupportedLocales: []string{"*"},
			NativeOptions:    []string{"context_prompt", "reasoning_effort", "turn_detection", "transcription_only", "translation"},
			AuthRequirement:  "api_key",
			Transport:        "websocket",
			EvidenceURL:      "https://learn.microsoft.com/azure/ai-foundry/openai/realtime-audio-quickstart",
			AdapterKind:      "foundry_realtime",
			Variants: []speechkit.ModelVariant{
				{ID: "foundry.gpt-realtime-2", Name: "GPT Realtime 2", ModelID: ModelOpenAIRealtime2, Recommended: true},
				{ID: "foundry.gpt-realtime-2.1", Name: "GPT Realtime 2.1 (Preview)", ModelID: "gpt-realtime-2.1"},
				{ID: "foundry.gpt-realtime-2.1-mini", Name: "GPT Realtime 2.1 mini (Preview)", ModelID: "gpt-realtime-2.1-mini"},
			},
			AllowInference: true,
			Recommended:    true,
		},
		{
			// Voice Live is Microsoft's managed voice agent on the same Foundry
			// resource: the brain is any of the models the service hosts (no
			// deployment needed), speech in comes from MAI-Transcribe, speech
			// out from a MAI-Voice-2 voice, with Azure semantic VAD, noise
			// suppression and echo cancellation on the server. The model id is
			// the brain; voice and transcription live in the Foundry settings.
			ID:            "realtime.foundry.voice-live",
			Mode:          speechkit.ModeVoiceAgent,
			Name:          "Microsoft Foundry Voice Live",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeFoundry,
			Provider:      "foundry-voicelive",
			ModelID:       "gpt-realtime-2",
			Lifecycle:     speechkit.ModelLifecycleGA,
			Source:        "Microsoft Foundry",
			Description:   "Microsoft-native realtime voice agent: Voice Live pairs a hosted brain model with MAI-Voice-2 speech output and MAI-Transcribe-2 input transcription, plus server-side semantic turn detection and noise suppression. The MAI voice and transcription models are public preview.",
			License:       "proprietary",
			Capabilities: []speechkit.Capability{
				speechkit.CapabilityAudioInput,
				speechkit.CapabilityRealtimeAudio,
				speechkit.CapabilityToolCalling,
				speechkit.CapabilityNativeContextPrompt,
				speechkit.CapabilityTranscript,
				speechkit.CapabilityInterruptions,
				speechkit.CapabilitySessionSummary,
			},
			SupportedLocales: []string{"*"},
			NativeOptions:    []string{"context_prompt", "turn_detection"},
			AuthRequirement:  "api_key",
			Transport:        "websocket",
			EvidenceURL:      "https://learn.microsoft.com/azure/ai-services/speech-service/voice-live",
			AdapterKind:      "foundry_voicelive",
			Variants: []speechkit.ModelVariant{
				{ID: "foundry.voicelive.gpt-realtime-2", Name: "GPT Realtime 2 brain", ModelID: "gpt-realtime-2", Recommended: true},
				{ID: "foundry.voicelive.gpt-realtime-mini", Name: "GPT Realtime mini brain", ModelID: "gpt-realtime-mini", Description: "Lower cost realtime brain."},
				{ID: "foundry.voicelive.gpt-5-mini", Name: "GPT-5 mini brain", ModelID: "gpt-5-mini", Description: "Text brain; Voice Live adds speech in and out."},
				{ID: "foundry.voicelive.phi4-mm-realtime", Name: "Phi-4 multimodal realtime brain", ModelID: "phi4-mm-realtime", Description: "Small Microsoft model for low-latency agents."},
			},
			AllowInference: true,
			Recommended:    true,
		},
		// ─── TTS (Voice Output) profile catalog ─────────────────────────────
		// Added in v0.37 alongside the hands-free Voice-Companion flow so
		// hosts pin a stable TTS voice per deployment ("Thalia speaks via
		// Studio-O", "Companion Live via OpenAI tts-1-hd Nova"). The four
		// ProviderKind groups follow the same V23 invariant as the other
		// modes: Local Built-in (Piper, shipped Phase 3), Local Provider
		// (OpenAI-compatible self-hosted via Kokoro/openedai-speech),
		// Cloud Provider (Hugging Face), Direct Provider (OpenAI + Google).
		// Kokoro-82M is the current Hugging Face TTS leader (68M downloads,
		// 6.1k likes as of 2026-05). Apache-2.0, ~82M parameters, ONNX
		// export available (~50 MB int8 / ~310 MB fp32). Best-in-class
		// English quality at very low compute. Bundled into the v0.37
		// installer as the recommended Local Built-in default. Phase-3
		// runtime: kokoro-onnx via onnxruntime-go subprocess wrapper.
		{
			ID:            "tts.local.kokoro-82m",
			Mode:          speechkit.ModeTTS,
			Name:          "Kokoro 82M (Local Built-in, recommended)",
			ProviderKind:  speechkit.ProviderKindLocalBuiltIn,
			ExecutionMode: speechkit.ExecutionModeLocal,
			ModelID:       "hexgrad/Kokoro-82M",
			Source:        "Local Built-in",
			Description:   "StyleTTS2-based Kokoro 82M. Apache-2.0, 68M+ Hugging Face downloads, ~50 MB ONNX (int8) — the recommended Local Built-in default for v0.37+. English voices ship in the installer; community v0.19/v1 forks add JP/DE/CN. Phase-3 runtime via onnxruntime-go sidecar.",
			License:       "apache-2.0",
			Capabilities:  []speechkit.Capability{speechkit.CapabilityTTS},
			AdapterKind:   "kokoro_local",
			Variants: []speechkit.ModelVariant{
				{ID: "kokoro.en.af-bella", Name: "Bella (EN, female)", ModelID: "kokoro-v1_0|af_bella", Recommended: true},
				{ID: "kokoro.en.af-nova", Name: "Nova (EN, female)", ModelID: "kokoro-v1_0|af_nova"},
				{ID: "kokoro.en.am-michael", Name: "Michael (EN, male)", ModelID: "kokoro-v1_0|am_michael"},
				{ID: "kokoro.en.bf-emma", Name: "Emma (BR-EN, female)", ModelID: "kokoro-v1_0|bf_emma"},
			},
			AllowInference: false,
			Default:        true,
			Recommended:    true,
			Experimental:   true,
		},
		// Supertonic-3 is the most-trended Hugging Face TTS model of
		// May 2026 (trending score 331). OpenRAIL license, ONNX, true
		// multilingual coverage (32 languages including DE/EN/JA/AR/KO).
		// Optimised for on-device inference. Phase-3 runtime via the
		// upstream `supertonic` Python library bridged through the
		// same sidecar pattern as Kokoro.
		{
			ID:            "tts.local.supertonic-3",
			Mode:          speechkit.ModeTTS,
			Name:          "Supertonic-3 (Local Built-in, multilingual)",
			ProviderKind:  speechkit.ProviderKindLocalBuiltIn,
			ExecutionMode: speechkit.ExecutionModeLocal,
			ModelID:       "Supertone/supertonic-3",
			Source:        "Local Built-in",
			Description:   "Supertonic-3 multilingual on-device TTS. OpenRAIL license, 32 languages with strong DE/EN/JA/AR/KO coverage. ONNX. Trending #3 on Hugging Face TTS leaderboard (May 2026). Phase-3 runtime via onnx sidecar.",
			License:       "openrail",
			Capabilities:  []speechkit.Capability{speechkit.CapabilityTTS},
			AdapterKind:   "supertonic_local",
			Variants: []speechkit.ModelVariant{
				{ID: "supertonic3.de.default", Name: "Standard (DE)", ModelID: "supertonic-3|de", Recommended: true},
				{ID: "supertonic3.en.default", Name: "Standard (EN)", ModelID: "supertonic-3|en"},
				{ID: "supertonic3.multilingual", Name: "Auto-language", ModelID: "supertonic-3|auto"},
			},
			AllowInference: false,
			Recommended:    true,
			Experimental:   true,
		},
		// Chatterbox-multilingual is the strongest open voice-cloning
		// TTS on Hugging Face. Same ONNX path as Kokoro/Supertonic.
		// Voice-cloning capability is the differentiator — useful for
		// kombify Companion personas that need a custom voice baked
		// from a short reference clip.
		{
			ID:            "tts.local.chatterbox-multilingual",
			Mode:          speechkit.ModeTTS,
			Name:          "Chatterbox Multilingual (Local Built-in, voice-clone)",
			ProviderKind:  speechkit.ProviderKindLocalBuiltIn,
			ExecutionMode: speechkit.ExecutionModeLocal,
			ModelID:       "onnx-community/chatterbox-multilingual-ONNX",
			Source:        "Local Built-in",
			Description:   "Chatterbox multilingual TTS with voice-cloning support. 24 languages (DE/EN/ES/FR/IT/JA/KO/...). ONNX, on-device. Phase-3 runtime via the same sidecar pattern as Kokoro; voice-clone reference clip configurable per Persona.",
			License:       "mit",
			Capabilities:  []speechkit.Capability{speechkit.CapabilityTTS},
			AdapterKind:   "chatterbox_local",
			Variants: []speechkit.ModelVariant{
				{ID: "chatterbox.de.default", Name: "Standard (DE)", ModelID: "chatterbox|de"},
				{ID: "chatterbox.en.default", Name: "Standard (EN)", ModelID: "chatterbox|en", Recommended: true},
				{ID: "chatterbox.clone", Name: "Custom voice clone", ModelID: "chatterbox|cloned"},
			},
			AllowInference: false,
			Experimental:   true,
		},
		// Piper retained as an additional Local Built-in option for the
		// Home-Assistant-aligned crowd — Piper is HA Voice's canonical
		// engine and many users have ready-made voice catalogs.
		{
			ID:            "tts.local.piper",
			Mode:          speechkit.ModeTTS,
			Name:          "Piper Local TTS (HA-compatible voices)",
			ProviderKind:  speechkit.ProviderKindLocalBuiltIn,
			ExecutionMode: speechkit.ExecutionModeLocal,
			Provider:      "piper",
			ModelID:       "rhasspy/piper",
			Source:        "Local Built-in",
			Description:   "Piper offline neural TTS — the canonical Home Assistant Voice engine. MIT-licensed, ~50 MB per voice, broad multilingual voice catalog. Runs through the SpeechKit piper subprocess adapter; configure binary and voice directory under [tts.piper].",
			License:       "mit",
			Capabilities:  []speechkit.Capability{speechkit.CapabilityTTS},
			AdapterKind:   "piper_local",
			Variants: []speechkit.ModelVariant{
				{ID: "piper.de.thorsten-medium", Name: "Thorsten (DE, Medium)", ModelID: "de_DE-thorsten-medium.onnx", Recommended: true},
				{ID: "piper.de.thorsten-high", Name: "Thorsten (DE, High)", ModelID: "de_DE-thorsten-high.onnx"},
				{ID: "piper.en.amy-medium", Name: "Amy (EN, Medium)", ModelID: "en_US-amy-medium.onnx"},
				{ID: "piper.en.lessac-medium", Name: "Lessac (EN, Medium)", ModelID: "en_US-lessac-medium.onnx"},
			},
			AllowInference: true,
		},
		{
			ID:             "tts.openedai.kokoro",
			Mode:           speechkit.ModeTTS,
			Name:           "Kokoro 82M (OpenAI-compatible local)",
			ProviderKind:   speechkit.ProviderKindLocalProvider,
			ExecutionMode:  speechkit.ExecutionModeSelfHostedHTTP,
			ModelID:        "kokoro-82m",
			Source:         "Local Provider",
			Description:    "Self-hosted Kokoro-82M TTS exposed through an OpenAI-compatible /v1/audio/speech endpoint (openedai-speech / similar). Configure URL + API key under [tts] manually until the readiness wizard lands.",
			License:        "apache-2.0",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityTTS},
			AdapterKind:    "openai_compatible_tts",
			AllowInference: true,
			Experimental:   true,
		},
		{
			ID:             "tts.huggingface.parler-multilingual",
			Mode:           speechkit.ModeTTS,
			Name:           "Parler-TTS Mini Multilingual (Hugging Face)",
			ProviderKind:   speechkit.ProviderKindCloudProvider,
			ExecutionMode:  speechkit.ExecutionModeHFRouted,
			ModelID:        "Qwen/Qwen3-TTS-12Hz-1.7B-Base",
			Source:         "Hugging Face",
			Description:    "Hugging Face Inference Router serves the Parler multilingual voice. Requires an HF token. Good baseline cloud option without OpenAI / Google credentials.",
			License:        "apache-2.0",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityTTS},
			AdapterKind:    "hf_tts",
			AllowInference: true,
		},
		{
			ID:            "tts.google.studio-o-de",
			Mode:          speechkit.ModeTTS,
			Name:          "Google Studio-O (DE-DE)",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeGoogle,
			ModelID:       "de-DE-Studio-O",
			Source:        "Google",
			Description:   "Google Cloud TTS Studio voices. Studio-O is the recommended German voice for the Thalia + Companion-Live use-cases. Requires a Google AI API key with the Text-to-Speech API enabled.",
			License:       "proprietary",
			Capabilities:  []speechkit.Capability{speechkit.CapabilityTTS},
			AdapterKind:   "google_tts",
			Variants: []speechkit.ModelVariant{
				{ID: "google.de.studio-o", Name: "Studio-O (DE)", ModelID: "de-DE-Studio-O", Recommended: true},
				{ID: "google.de.studio-q", Name: "Studio-Q (DE)", ModelID: "de-DE-Studio-Q"},
				{ID: "google.de.wavenet-f", Name: "Wavenet-F (DE)", ModelID: "de-DE-Wavenet-F"},
				{ID: "google.en.studio-o", Name: "Studio-O (EN-US)", ModelID: "en-US-Studio-O"},
			},
			AllowInference: true,
			Recommended:    true,
			// Default=true moved to tts.local.kokoro-82m in v0.37.3 — the
			// Local Built-in winner is now the catalog default. Google
			// Studio-O DE remains the DefaultTTSPrimaryProfileID config
			// constant for installs that already have GOOGLE_AI_API_KEY.
		},
		{
			ID:            "tts.deepgram.aura-2",
			Mode:          speechkit.ModeTTS,
			Name:          "Deepgram Aura-2",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeDeepgram,
			ModelID:       "aura-2-thalia-en",
			Source:        "Deepgram",
			Description:   "Deepgram Aura-2 low-latency neural TTS. Recommended Voice-Output path for kombify reference deployments; English + German voices over the single DEEPGRAM_API_KEY shared with Deepgram STT and the Voice Agent.",
			License:       "proprietary",
			Capabilities:  []speechkit.Capability{speechkit.CapabilityTTS},
			AdapterKind:   "deepgram_tts",
			Variants: []speechkit.ModelVariant{
				{ID: "deepgram.aura2.thalia-en", Name: "Thalia (EN, female)", ModelID: "aura-2-thalia-en", Recommended: true},
				{ID: "deepgram.aura2.apollo-en", Name: "Apollo (EN, male)", ModelID: "aura-2-apollo-en"},
				{ID: "deepgram.aura2.viktoria-de", Name: "Viktoria (DE, female)", ModelID: "aura-2-viktoria-de"},
				{ID: "deepgram.aura2.julius-de", Name: "Julius (DE, male)", ModelID: "aura-2-julius-de"},
			},
			AllowInference: true,
			Recommended:    true,
		},
		{
			ID:            "tts.openai.tts-1-hd",
			Mode:          speechkit.ModeTTS,
			Name:          "OpenAI TTS-1-HD",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeOpenAI,
			ModelID:       "tts-1-hd",
			Source:        "OpenAI",
			Description:   "OpenAI's high-definition TTS. Pricier than tts-1 but higher voice quality. Six built-in voices (alloy, echo, fable, onyx, nova, shimmer). Requires an OpenAI API key.",
			License:       "proprietary",
			Capabilities:  []speechkit.Capability{speechkit.CapabilityTTS},
			AdapterKind:   "openai_tts",
			Variants: []speechkit.ModelVariant{
				{ID: "openai.tts1hd.nova", Name: "Nova (HD)", ModelID: "tts-1-hd|nova", Recommended: true},
				{ID: "openai.tts1hd.shimmer", Name: "Shimmer (HD)", ModelID: "tts-1-hd|shimmer"},
				{ID: "openai.tts1hd.alloy", Name: "Alloy (HD)", ModelID: "tts-1-hd|alloy"},
				{ID: "openai.tts1.nova", Name: "Nova (Standard)", ModelID: "tts-1|nova"},
			},
			AllowInference: true,
			Recommended:    true,
		},
		{
			ID:            "tts.foundry.gpt-4o-mini-tts",
			Mode:          speechkit.ModeTTS,
			Name:          "GPT-4o mini TTS (Microsoft Foundry)",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeFoundry,
			Provider:      "foundry",
			ModelID:       "gpt-4o-mini-tts",
			Source:        "Microsoft Foundry",
			Description:   "Azure-hosted steerable TTS through the Microsoft Foundry OpenAI-compatible audio/speech endpoint. The model id is the default deployment name — override deployment and voice in the Foundry integration settings.",
			License:       "proprietary",
			Capabilities:  []speechkit.Capability{speechkit.CapabilityTTS},
			AdapterKind:   "foundry_tts",
			EvidenceURL:   "https://learn.microsoft.com/azure/ai-foundry/openai/reference",
			Variants: []speechkit.ModelVariant{
				{ID: "foundry.gpt-4o-mini-tts.alloy", Name: "Alloy (GPT-4o mini TTS)", ModelID: "gpt-4o-mini-tts|alloy", Recommended: true},
				{ID: "foundry.gpt-4o-mini-tts.nova", Name: "Nova (GPT-4o mini TTS)", ModelID: "gpt-4o-mini-tts|nova"},
				{ID: "foundry.tts.alloy", Name: "Alloy (TTS Standard)", ModelID: "tts|alloy"},
				{ID: "foundry.tts-hd.nova", Name: "Nova (TTS HD)", ModelID: "tts-hd|nova"},
			},
			AllowInference: true,
			Recommended:    true,
		},
		{
			// MAI-Voice-2 voices are Azure Speech voices on the same Foundry
			// resource (SSML on the Cognitive Services host), not audio/speech
			// deployments. Variant ids follow the "<family>|<voice>" shape of
			// the other TTS profiles; the voice is a Speech short name.
			ID:            "tts.foundry.mai-voice-2",
			Mode:          speechkit.ModeTTS,
			Name:          "MAI-Voice-2 (Microsoft Foundry)",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeFoundry,
			Provider:      "foundry",
			ModelID:       "MAI-Voice-2",
			Lifecycle:     speechkit.ModelLifecyclePreview,
			Source:        "Microsoft Foundry",
			Description:   "Microsoft's expressive text to speech through Azure Speech on the Foundry resource. MAI-Voice-2 is the high-fidelity voice family, MAI-Voice-2-Flash the low-latency one for agents; both offer 18 locales and emotion styles. Public preview.",
			License:       "proprietary",
			Capabilities:  []speechkit.Capability{speechkit.CapabilityTTS},
			AdapterKind:   "foundry_tts",
			EvidenceURL:   "https://learn.microsoft.com/azure/ai-services/speech-service/mai-voices",
			Variants: []speechkit.ModelVariant{
				{ID: "foundry.mai-voice-2.de-mia", Name: "Mia, German (MAI-Voice-2)", ModelID: "MAI-Voice-2|de-DE-Mia:MAI-Voice-2", Recommended: true},
				{ID: "foundry.mai-voice-2.de-klaus", Name: "Klaus, German (MAI-Voice-2)", ModelID: "MAI-Voice-2|de-DE-Klaus:MAI-Voice-2"},
				{ID: "foundry.mai-voice-2.en-harper", Name: "Harper, English US (MAI-Voice-2)", ModelID: "MAI-Voice-2|en-US-Harper:MAI-Voice-2"},
				{ID: "foundry.mai-voice-2.en-ethan", Name: "Ethan, English US (MAI-Voice-2)", ModelID: "MAI-Voice-2|en-US-Ethan:MAI-Voice-2"},
				{ID: "foundry.mai-voice-2-flash.de-mia", Name: "Mia, German (MAI-Voice-2-Flash)", ModelID: "MAI-Voice-2-Flash|de-DE-Mia:MAI-Voice-2-Flash", Description: "Low-latency variant for Voice Agent read-back."},
				{ID: "foundry.mai-voice-2-flash.en-ethan", Name: "Ethan, English US (MAI-Voice-2-Flash)", ModelID: "MAI-Voice-2-Flash|en-US-Ethan:MAI-Voice-2-Flash", Description: "Low-latency variant for Voice Agent read-back."},
			},
			AllowInference: true,
			Recommended:    true,
			Experimental:   true,
		},
	}
	for i := range profiles {
		profiles[i] = ProviderProfileWithDefaults(profiles[i])
	}
	return profiles
}

func ProfilesForMode(mode speechkit.Mode) []speechkit.ProviderProfile {
	mode = speechkit.NormalizeMode(mode)
	var profiles []speechkit.ProviderProfile
	for _, profile := range DefaultProviderProfiles() {
		if speechkit.NormalizeMode(profile.Mode) == mode {
			profiles = append(profiles, profile)
		}
	}
	return profiles
}

func ProviderKindsForMode(mode speechkit.Mode) []speechkit.ProviderKind {
	seen := map[speechkit.ProviderKind]bool{}
	for _, profile := range ProfilesForMode(mode) {
		seen[profile.ProviderKind] = true
	}
	kinds := make([]speechkit.ProviderKind, 0, len(seen))
	for _, kind := range []speechkit.ProviderKind{
		speechkit.ProviderKindLocalBuiltIn,
		speechkit.ProviderKindLocalProvider,
		speechkit.ProviderKindCloudProvider,
		speechkit.ProviderKindDirectProvider,
	} {
		if seen[kind] {
			kinds = append(kinds, kind)
		}
	}
	return kinds
}

// ValidateDefaultCatalog verifies the framework invariant that every strict
// mode exposes all four provider groups and every visible profile satisfies its
// mode contract. v0.37 added ModeTTS as a model-selection axis with the same
// four-provider-group invariant (Local Built-in via Piper, Local Provider
// via Kokoro/openedai-speech, Cloud Provider via Hugging Face Parler, Direct
// Provider via OpenAI + Google).
func ValidateDefaultCatalog() error {
	for _, mode := range []speechkit.Mode{speechkit.ModeDictation, speechkit.ModeAssist, speechkit.ModeVoiceAgent, speechkit.ModeTTS} {
		kinds := ProviderKindsForMode(mode)
		if len(kinds) != 4 {
			sort.Slice(kinds, func(i, j int) bool { return kinds[i] < kinds[j] })
			return catalogContractError{mode: mode, kinds: kinds}
		}
		for _, profile := range ProfilesForMode(mode) {
			if err := speechkit.ValidateProfileForMode(profile, mode); err != nil {
				return err
			}
		}
	}
	return nil
}

type catalogContractError struct {
	mode  speechkit.Mode
	kinds []speechkit.ProviderKind
}

func (e catalogContractError) Error() string {
	return "speechkit: default catalog does not expose four provider groups for " + string(e.mode)
}
