package catalog

import (
	"github.com/kombifyio/SpeechKit/pkg/speechkit"
)

// dictationProviderProfiles returns the built-in Dictation (speech-to-text)
// section of the default provider catalog.
func dictationProviderProfiles() []speechkit.ProviderProfile {
	return []speechkit.ProviderProfile{
		{
			ID:            "stt.local.whispercpp",
			Mode:          speechkit.ModeDictation,
			Name:          "Whisper.cpp (Local Built-in)",
			ProviderKind:  speechkit.ProviderKindLocalBuiltIn,
			ExecutionMode: speechkit.ExecutionModeLocal,
			ModelID:       "whisper.cpp",
			Source:        "Local Built-in",
			Description:   "SpeechKit-managed local runtime for Transcribe. Download options provide the concrete Whisper-compatible transcription models.",
			License:       "mit",
			Capabilities:  []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryPrompt},
			AdapterKind:   "stt_router",
			Variants: []speechkit.ModelVariant{
				{ID: "whisper.ggml-small", Name: "Whisper Small Multilingual", ModelID: "ggml-small.bin"},
				{ID: "whisper.ggml-large-v3-turbo", Name: "Whisper Large v3 Turbo", ModelID: "ggml-large-v3-turbo.bin", Recommended: true},
				{ID: "whisper.ggml-large-v3", Name: "Whisper Large v3", ModelID: "ggml-large-v3.bin"},
			},
			AllowInference: false,
			Default:        true,
			Recommended:    true,
		},
		{
			ID:            "stt.ollama.gemma4-e4b-transcribe",
			Mode:          speechkit.ModeDictation,
			Name:          "Gemma 4 E4B Transcribe (Ollama)",
			ProviderKind:  speechkit.ProviderKindLocalProvider,
			ExecutionMode: speechkit.ExecutionModeOllama,
			ModelID:       "gemma4:e4b",
			Source:        "Local Provider",
			Description:   "User-managed Ollama provider through SpeechKit's constrained Dictation adapter. Audio in, transcription text out; Gemma 4 accepts clips of up to 30 seconds.",
			License:       "gemma",
			Capabilities:  []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryPrompt},
			AdapterKind:   "ollama_transcription",
			Variants: []speechkit.ModelVariant{
				{ID: "ollama.gemma4-e4b", Name: "Gemma 4 E4B", ModelID: "gemma4:e4b", Recommended: true},
				{ID: "ollama.gemma4-12b", Name: "Gemma 4 12B", ModelID: "gemma4:12b", Description: "Larger unified Gemma 4 with native audio input for hosts with enough memory."},
			},
			AllowInference: true,
			Experimental:   true,
		},
		{
			ID:             "stt.routed.whisper-large-v3",
			Mode:           speechkit.ModeDictation,
			Name:           "Whisper Large v3 Turbo (Hugging Face)",
			ProviderKind:   speechkit.ProviderKindCloudProvider,
			ExecutionMode:  speechkit.ExecutionModeHFRouted,
			ModelID:        "openai/whisper-large-v3-turbo",
			Source:         "Hugging Face",
			Description:    "Fast multilingual transcription over the Hugging Face Inference Router. Requires an HF token.",
			License:        "mit",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryPrompt},
			AdapterKind:    "stt_router",
			AllowInference: true,
			Recommended:    true,
		},
		{
			ID:             "stt.openrouter.gpt-transcribe",
			Mode:           speechkit.ModeDictation,
			Name:           "GPT Transcribe (OpenRouter)",
			ProviderKind:   speechkit.ProviderKindCloudProvider,
			ExecutionMode:  speechkit.ExecutionModeOpenRouter,
			ModelID:        modelOpenRouterGPTTranscribe,
			Source:         "OpenRouter",
			Description:    "Gateway-routed transcription through OpenRouter's speech-to-text endpoint, using OpenAI's current gpt-transcribe model.",
			License:        "proprietary",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryPrompt},
			AdapterKind:    "openrouter_stt",
			AllowInference: true,
		},
		{
			ID:             "stt.openai.gpt-transcribe",
			Mode:           speechkit.ModeDictation,
			Name:           "GPT Transcribe (OpenAI)",
			ProviderKind:   speechkit.ProviderKindDirectProvider,
			ExecutionMode:  speechkit.ExecutionModeOpenAI,
			ModelID:        modelOpenAIGPTTranscribe,
			Lifecycle:      speechkit.ModelLifecycleGA,
			Source:         "OpenAI",
			Description:    "OpenAI's current file transcription model for dictation and meeting audio when an OpenAI API key is configured; live dictation streams over a Realtime transcription session on gpt-live-transcribe. Words & Replacements ride as native keywords. It replaces the deprecated gpt-4o transcribe family and whisper-1.",
			License:        "proprietary",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryPrompt, speechkit.CapabilityNativeDictationStream},
			AdapterKind:    "stt_router",
			EvidenceURL:    "https://developers.openai.com/api/docs/models/gpt-transcribe",
			AllowInference: true,
			Default:        true,
			Recommended:    true,
		},
		{
			// The current OpenAI file-transcription model on Foundry (the
			// model list marks the gpt-4o transcribe family as preview and
			// gpt-transcribe as the offline model for /audio/transcriptions).
			// It needs a deployment of that name; the MAI profile below needs
			// none and is the recommended default.
			ID:            "stt.foundry.gpt-transcribe",
			Mode:          speechkit.ModeDictation,
			Name:          "GPT Transcribe (Microsoft Foundry)",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeFoundry,
			Provider:      "foundry",
			ModelID:       "gpt-transcribe",
			Lifecycle:     speechkit.ModelLifecycleGA,
			Source:        "Microsoft Foundry",
			Description:   "Azure-hosted transcription through the Microsoft Foundry OpenAI-compatible v1 surface. The model id is the default deployment name — override it with your own deployment name in the Foundry integration settings.",
			License:       "proprietary",
			Capabilities:  []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryPrompt},
			AdapterKind:   "stt_router",
			EvidenceURL:   "https://learn.microsoft.com/azure/ai-foundry/openai/concepts/models",
			Variants: []speechkit.ModelVariant{
				{ID: "foundry.gpt-transcribe", Name: "GPT Transcribe", ModelID: "gpt-transcribe", Recommended: true},
			},
			AllowInference: true,
		},
		{
			// MAI-Transcribe is served by the Azure Speech surface of the same
			// Foundry resource (fast transcription with enhancedMode), not by
			// a deployment. The model id is sent verbatim; no deployment
			// exists to rename.
			ID:            "stt.foundry.mai-transcribe-2",
			Mode:          speechkit.ModeDictation,
			Name:          "MAI-Transcribe-2 (Microsoft Foundry)",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeFoundry,
			Provider:      "foundry",
			ModelID:       "MAI-Transcribe-2",
			Lifecycle:     speechkit.ModelLifecyclePreview,
			Source:        "Microsoft Foundry",
			Description:   "Microsoft's own speech recognition model through Azure Speech fast transcription on the Foundry resource: 60 languages with automatic language detection, speaker diarization, clean or verbatim transcripts and phrase biasing from Words & Replacements. Public preview.",
			License:       "proprietary",
			Capabilities:  []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryPrompt},
			AdapterKind:   "stt_router",
			EvidenceURL:   "https://learn.microsoft.com/azure/ai-services/speech-service/mai-transcribe",
			Variants: []speechkit.ModelVariant{
				{ID: "foundry.mai-transcribe-2", Name: "MAI-Transcribe-2 (Preview)", ModelID: "MAI-Transcribe-2", Recommended: true},
			},
			AllowInference: true,
			Recommended:    true,
			Experimental:   true,
		},
		{
			ID:             "stt.google.latest-long",
			Mode:           speechkit.ModeDictation,
			Name:           "Latest Long (Google STT)",
			ProviderKind:   speechkit.ProviderKindDirectProvider,
			ExecutionMode:  speechkit.ExecutionModeGoogle,
			ModelID:        "latest_long",
			Source:         "Google Cloud Speech-to-Text",
			Description:    "Opt-in Google Cloud Speech-to-Text with your own credentials. Requires a dedicated Google STT key (SPEECHKIT_GOOGLE_STT_API_KEY) or service-account/ADC credentials; the Gemini GOOGLE_AI_API_KEY does not enable this profile by itself. Never a default.",
			License:        "proprietary",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryNativeHints, speechkit.CapabilitySpeakerDiarization},
			AdapterKind:    "stt_router",
			AllowInference: true,
		},
		{
			ID:             "stt.google.latest-long-diarization",
			Mode:           speechkit.ModeDictation,
			Name:           "Latest Long Diarization (Google STT)",
			ProviderKind:   speechkit.ProviderKindDirectProvider,
			ExecutionMode:  speechkit.ExecutionModeGoogle,
			ModelID:        "latest_long",
			Source:         "Google Cloud Speech-to-Text",
			Description:    "Opt-in Google Cloud Speech-to-Text with optional word-level speaker diarization, using your own SPEECHKIT_GOOGLE_STT_API_KEY; GOOGLE_AI_API_KEY is not enough for this STT profile. Never a default.",
			License:        "proprietary",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryNativeHints, speechkit.CapabilitySpeakerDiarization},
			AdapterKind:    "stt_router",
			AllowInference: true,
		},
		{
			// Chirp 3 runs only on Speech-to-Text v2 in the us and eu
			// multi-regions; [providers.google] region picks which. Batch
			// recognition diarizes, streaming does not.
			ID:             "stt.google.chirp-3",
			Mode:           speechkit.ModeDictation,
			Name:           "Chirp 3 (Google STT)",
			ProviderKind:   speechkit.ProviderKindDirectProvider,
			ExecutionMode:  speechkit.ExecutionModeGoogle,
			ModelID:        "chirp_3",
			Lifecycle:      speechkit.ModelLifecycleGA,
			Source:         "Google Cloud Speech-to-Text",
			Description:    "Google's current speech model on Speech-to-Text v2 (us or eu multi-region, from [providers.google] region) with speech adaptation and batch speaker diarization. Opt-in with your own service-account or ADC credentials (SPEECHKIT_GOOGLE_STT_CREDENTIALS_JSON or GOOGLE_APPLICATION_CREDENTIALS) and a Google Cloud project: Speech-to-Text v2 does not accept API keys. Never a default.",
			License:        "proprietary",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryNativeHints, speechkit.CapabilitySpeakerDiarization},
			AdapterKind:    "stt_router",
			EvidenceURL:    "https://docs.cloud.google.com/speech-to-text/docs/models/chirp-3",
			AllowInference: true,
			Recommended:    true,
		},
		{
			// Gemini Transcribe runs on the Gemini API Interactions endpoint
			// with the Gemini API key, not on Cloud Speech-to-Text.
			ID:             "stt.google.gemini-3.5-transcribe",
			Mode:           speechkit.ModeDictation,
			Name:           "Gemini 3.5 Transcribe (Google)",
			ProviderKind:   speechkit.ProviderKindDirectProvider,
			ExecutionMode:  speechkit.ExecutionModeGoogle,
			Provider:       "google",
			ModelID:        modelGemini35Transcribe,
			Lifecycle:      speechkit.ModelLifecycleGA,
			Source:         "Google Gemini API",
			Description:    "Opt-in Gemini Transcribe with your own GOOGLE_AI_API_KEY: smart transcription removes fillers and resolves self-corrections, Words & Replacements ride as custom vocabulary, and unpinned sessions auto-detect the language. Audio goes inline and is not stored; live dictation streams on gemini-3.5-transcribe-live over the Gemini Live API. Never a default.",
			License:        "proprietary",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryNativeHints, speechkit.CapabilityNativeDictationStream},
			AdapterKind:    "gemini_transcribe",
			EvidenceURL:    "https://ai.google.dev/gemini-api/docs/models/gemini-3.5-transcribe",
			AllowInference: true,
			Experimental:   true,
		},
		{
			ID:             "stt.deepgram.nova-3",
			Mode:           speechkit.ModeDictation,
			Name:           "Nova-3 (Deepgram)",
			ProviderKind:   speechkit.ProviderKindDirectProvider,
			ExecutionMode:  speechkit.ExecutionModeDeepgram,
			ModelID:        "nova-3",
			Source:         "Deepgram",
			Description:    "Deepgram-hosted Nova-3 transcription. Low-latency streaming + batch STT; the recommended first-level cloud transcription path for kombify reference deployments.",
			License:        "proprietary",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryPrompt, speechkit.CapabilityNativeDictationStream},
			AdapterKind:    "deepgram_stt",
			AllowInference: true,
			Recommended:    true,
		},
		{
			ID:             "stt.deepgram.nova-3-diarization",
			Mode:           speechkit.ModeDictation,
			Name:           "Nova-3 Diarization (Deepgram)",
			ProviderKind:   speechkit.ProviderKindDirectProvider,
			ExecutionMode:  speechkit.ExecutionModeDeepgram,
			ModelID:        "nova-3",
			Source:         "Deepgram",
			Description:    "Deepgram-hosted transcription with diarize_model=latest for batch speaker labels and word-level speaker confidence.",
			License:        "proprietary",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilitySpeakerDiarization},
			AdapterKind:    "deepgram_stt",
			AllowInference: true,
			Recommended:    true,
		},
		{
			ID:             "stt.assemblyai.universal",
			Mode:           speechkit.ModeDictation,
			Name:           "Universal-3.5 Pro (AssemblyAI)",
			ProviderKind:   speechkit.ProviderKindDirectProvider,
			ExecutionMode:  speechkit.ExecutionModeAssemblyAI,
			ModelID:        "universal-3-5-pro,universal-2",
			Source:         "AssemblyAI",
			Description:    "AssemblyAI Universal-3.5 Pro. Short clips ride the synchronous endpoint (finished transcript in one request, ~134 ms p50) with prompt steering, keyterms, and conversation context; longer or feature-rich requests use the async flow, and realtime dictation streams over v3 on Universal-3.6 Pro Realtime (32 languages) with agent context. The diarization variant adds speaker labels and content-based speaker identification by name/role.",
			License:        "proprietary",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryPrompt, speechkit.CapabilityNativeContextPrompt, speechkit.CapabilityNativeDictationStream},
			AdapterKind:    "assemblyai_stt",
			AllowInference: true,
			Recommended:    true,
		},
		{
			ID:             "stt.assemblyai.universal-diarization",
			Mode:           speechkit.ModeDictation,
			Name:           "Universal-3.5 Pro Diarization + Speaker Identification (AssemblyAI)",
			ProviderKind:   speechkit.ProviderKindDirectProvider,
			ExecutionMode:  speechkit.ExecutionModeAssemblyAI,
			ModelID:        "universal-3-5-pro,universal-2",
			Source:         "AssemblyAI",
			Description:    "AssemblyAI pre-recorded transcription with speaker_labels and optional content-based speaker identification by known names or roles. Diarization requests always use the async flow (the sync endpoint does not diarize).",
			License:        "proprietary",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilitySpeakerDiarization, speechkit.CapabilitySpeakerIdentification, speechkit.CapabilitySpeakerAttribution},
			AdapterKind:    "assemblyai_stt",
			AllowInference: true,
			Recommended:    true,
		},
		{
			ID:            "stt.groq.whisper-large-v3-turbo",
			Mode:          speechkit.ModeDictation,
			Name:          "Whisper Large v3 Turbo (Groq)",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeGroq,
			ModelID:       modelGroqWhisperLargeV3Turbo,
			Source:        "Groq",
			Description:   "Fast direct API transcription profile for low-latency dictation fallbacks.",
			License:       "proprietary",
			Capabilities:  []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryPrompt},
			AdapterKind:   "stt_router",
			EvidenceURL:   "https://console.groq.com/docs/speech-to-text",
			Variants: []speechkit.ModelVariant{
				{ID: "groq.whisper-large-v3-turbo", Name: "Whisper Large v3 Turbo", ModelID: modelGroqWhisperLargeV3Turbo, Recommended: true},
				{ID: "groq.whisper-large-v3", Name: "Whisper Large v3", ModelID: modelGroqWhisperLargeV3, Description: "Higher-accuracy Groq STT option for hosts that prefer quality over the turbo profile."},
			},
			AllowInference: true,
			Recommended:    true,
		},
	}
}
