package catalog

import (
	"github.com/kombifyio/SpeechKit/pkg/speechkit"
)

// dictationProviderProfiles returns the built-in Dictation (speech-to-text)
// section of the default provider catalog.
func dictationProviderProfiles() []speechkit.ProviderProfile {
	return []speechkit.ProviderProfile{
		{
			ID:            "stt.local.whispercpp",
			Mode:          speechkit.ModeDictation,
			Name:          "Whisper.cpp (Local Built-in)",
			ProviderKind:  speechkit.ProviderKindLocalBuiltIn,
			ExecutionMode: speechkit.ExecutionModeLocal,
			ModelID:       "whisper.cpp",
			Source:        "Local Built-in",
			Description:   "SpeechKit-managed local runtime for Transcribe. Download options provide the concrete Whisper-compatible transcription models.",
			License:       "mit",
			Capabilities:  []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryPrompt},
			AdapterKind:   "stt_router",
			Variants: []speechkit.ModelVariant{
				{ID: "whisper.ggml-small", Name: "Whisper Small Multilingual", ModelID: "ggml-small.bin"},
				{ID: "whisper.ggml-large-v3-turbo", Name: "Whisper Large v3 Turbo", ModelID: "ggml-large-v3-turbo.bin", Recommended: true},
				{ID: "whisper.ggml-large-v3", Name: "Whisper Large v3", ModelID: "ggml-large-v3.bin"},
			},
			AllowInference: false,
			Default:        true,
			Recommended:    true,
		},
		{
			ID:             "stt.ollama.gemma4-e4b-transcribe",
			Mode:           speechkit.ModeDictation,
			Name:           "Gemma 4 E4B Transcribe (Ollama)",
			ProviderKind:   speechkit.ProviderKindLocalProvider,
			ExecutionMode:  speechkit.ExecutionModeOllama,
			ModelID:        "gemma4:e4b",
			Source:         "Local Provider",
			Description:    "User-managed Ollama provider through SpeechKit's constrained Dictation adapter. Audio in, transcription text out.",
			License:        "gemma",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryPrompt},
			AdapterKind:    "ollama_transcription",
			AllowInference: true,
			Experimental:   true,
		},
		{
			ID:             "stt.routed.whisper-large-v3",
			Mode:           speechkit.ModeDictation,
			Name:           "Whisper Large v3 Turbo (Hugging Face)",
			ProviderKind:   speechkit.ProviderKindCloudProvider,
			ExecutionMode:  speechkit.ExecutionModeHFRouted,
			ModelID:        "openai/whisper-large-v3-turbo",
			Source:         "Hugging Face",
			Description:    "Fast multilingual transcription over the Hugging Face Inference Router. Requires an HF token.",
			License:        "mit",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryPrompt},
			AdapterKind:    "stt_router",
			AllowInference: true,
			Recommended:    true,
		},
		{
			ID:             "stt.openrouter.whisper-1",
			Mode:           speechkit.ModeDictation,
			Name:           "Whisper-1 (OpenRouter)",
			ProviderKind:   speechkit.ProviderKindCloudProvider,
			ExecutionMode:  speechkit.ExecutionModeOpenRouter,
			ModelID:        "openai/whisper-1",
			Source:         "OpenRouter",
			Description:    "Gateway-routed transcription through OpenRouter's speech-to-text endpoint.",
			License:        "apache-2.0",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryPrompt},
			AdapterKind:    "openrouter_stt",
			AllowInference: true,
		},
		{
			ID:            "stt.openai.gpt-4o-transcribe",
			Mode:          speechkit.ModeDictation,
			Name:          "GPT-4o Transcribe (OpenAI)",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeOpenAI,
			ModelID:       ModelOpenAIGPT4OTranscribe,
			Lifecycle:     speechkit.ModelLifecycleGA,
			Source:        "OpenAI",
			Description:   "Current OpenAI direct transcription profile for long dictation and meeting audio when an OpenAI API key is configured. Speaker diarization is kept out of this profile until the adapter maps diarized_json segments.",
			License:       "proprietary",
			Capabilities:  []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryPrompt},
			AdapterKind:   "stt_router",
			EvidenceURL:   "https://platform.openai.com/docs/guides/speech-to-text",
			Variants: []speechkit.ModelVariant{
				{ID: "openai.gpt-4o-transcribe", Name: "GPT-4o Transcribe", ModelID: ModelOpenAIGPT4OTranscribe, Recommended: true},
				{ID: "openai.gpt-4o-mini-transcribe", Name: "GPT-4o mini Transcribe", ModelID: ModelOpenAIGPT4OMiniTranscribe},
				{ID: "openai.gpt-4o-transcribe-diarize", Name: "GPT-4o Transcribe Diarize", ModelID: ModelOpenAIGPT4OTranscribeDiarize, Description: "Catalog-only variant until SpeechKit maps diarized_json speaker segments."},
				{ID: "openai.whisper-1", Name: "Whisper-1", ModelID: "whisper-1", Description: "Legacy fallback for older OpenAI-compatible deployments."},
			},
			AllowInference: true,
			Default:        true,
			Recommended:    true,
		},
		{
			ID:             "stt.openai.whisper-1",
			Mode:           speechkit.ModeDictation,
			Name:           "Whisper-1 (OpenAI)",
			ProviderKind:   speechkit.ProviderKindDirectProvider,
			ExecutionMode:  speechkit.ExecutionModeOpenAI,
			ModelID:        "whisper-1",
			Lifecycle:      speechkit.ModelLifecycleLegacy,
			Source:         "OpenAI",
			Description:    "Legacy direct transcription fallback for older deployments that still pin OpenAI whisper-1.",
			License:        "apache-2.0",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryPrompt},
			AdapterKind:    "stt_router",
			EvidenceURL:    "https://platform.openai.com/docs/guides/speech-to-text",
			AllowInference: true,
		},
		{
			// The current OpenAI file-transcription model on Foundry (the
			// model list marks the gpt-4o transcribe family as preview and
			// gpt-transcribe as the offline model for /audio/transcriptions).
			// It needs a deployment of that name; the MAI profile below needs
			// none and is the recommended default.
			ID:            "stt.foundry.gpt-transcribe",
			Mode:          speechkit.ModeDictation,
			Name:          "GPT Transcribe (Microsoft Foundry)",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeFoundry,
			Provider:      "foundry",
			ModelID:       "gpt-transcribe",
			Lifecycle:     speechkit.ModelLifecycleGA,
			Source:        "Microsoft Foundry",
			Description:   "Azure-hosted transcription through the Microsoft Foundry OpenAI-compatible v1 surface. The model id is the default deployment name — override it with your own deployment name in the Foundry integration settings.",
			License:       "proprietary",
			Capabilities:  []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryPrompt},
			AdapterKind:   "stt_router",
			EvidenceURL:   "https://learn.microsoft.com/azure/ai-foundry/openai/concepts/models",
			Variants: []speechkit.ModelVariant{
				{ID: "foundry.gpt-transcribe", Name: "GPT Transcribe", ModelID: "gpt-transcribe", Recommended: true},
			},
			AllowInference: true,
		},
		{
			// MAI-Transcribe is served by the Azure Speech surface of the same
			// Foundry resource (fast transcription with enhancedMode), not by
			// a deployment. The model id is sent verbatim; no deployment
			// exists to rename.
			ID:            "stt.foundry.mai-transcribe-2",
			Mode:          speechkit.ModeDictation,
			Name:          "MAI-Transcribe-2 (Microsoft Foundry)",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeFoundry,
			Provider:      "foundry",
			ModelID:       "MAI-Transcribe-2",
			Lifecycle:     speechkit.ModelLifecyclePreview,
			Source:        "Microsoft Foundry",
			Description:   "Microsoft's own speech recognition model through Azure Speech fast transcription on the Foundry resource: 60 languages with automatic language detection, speaker diarization, clean or verbatim transcripts and phrase biasing from Words & Replacements. Public preview.",
			License:       "proprietary",
			Capabilities:  []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryPrompt},
			AdapterKind:   "stt_router",
			EvidenceURL:   "https://learn.microsoft.com/azure/ai-services/speech-service/mai-transcribe",
			Variants: []speechkit.ModelVariant{
				{ID: "foundry.mai-transcribe-2", Name: "MAI-Transcribe-2 (Preview)", ModelID: "MAI-Transcribe-2", Recommended: true},
			},
			AllowInference: true,
			Recommended:    true,
			Experimental:   true,
		},
		{
			ID:             "stt.google.latest-long",
			Mode:           speechkit.ModeDictation,
			Name:           "Latest Long (Google STT)",
			ProviderKind:   speechkit.ProviderKindDirectProvider,
			ExecutionMode:  speechkit.ExecutionModeGoogle,
			ModelID:        "latest_long",
			Source:         "Google Cloud Speech-to-Text",
			Description:    "Opt-in Google Cloud Speech-to-Text with your own credentials. Requires a dedicated Google STT key (SPEECHKIT_GOOGLE_STT_API_KEY) or service-account/ADC credentials; the Gemini GOOGLE_AI_API_KEY does not enable this profile by itself. Never a default.",
			License:        "proprietary",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryNativeHints, speechkit.CapabilitySpeakerDiarization},
			AdapterKind:    "stt_router",
			AllowInference: true,
		},
		{
			ID:             "stt.google.latest-long-diarization",
			Mode:           speechkit.ModeDictation,
			Name:           "Latest Long Diarization (Google STT)",
			ProviderKind:   speechkit.ProviderKindDirectProvider,
			ExecutionMode:  speechkit.ExecutionModeGoogle,
			ModelID:        "latest_long",
			Source:         "Google Cloud Speech-to-Text",
			Description:    "Opt-in Google Cloud Speech-to-Text with optional word-level speaker diarization, using your own SPEECHKIT_GOOGLE_STT_API_KEY; GOOGLE_AI_API_KEY is not enough for this STT profile. Never a default.",
			License:        "proprietary",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryNativeHints, speechkit.CapabilitySpeakerDiarization},
			AdapterKind:    "stt_router",
			AllowInference: true,
		},
		{
			ID:             "stt.deepgram.nova-3",
			Mode:           speechkit.ModeDictation,
			Name:           "Nova-3 (Deepgram)",
			ProviderKind:   speechkit.ProviderKindDirectProvider,
			ExecutionMode:  speechkit.ExecutionModeDeepgram,
			ModelID:        "nova-3",
			Source:         "Deepgram",
			Description:    "Deepgram-hosted Nova-3 transcription. Low-latency streaming + batch STT; the recommended first-level cloud transcription path for kombify reference deployments.",
			License:        "proprietary",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryPrompt, speechkit.CapabilityNativeDictationStream},
			AdapterKind:    "deepgram_stt",
			AllowInference: true,
			Recommended:    true,
		},
		{
			ID:             "stt.deepgram.nova-3-diarization",
			Mode:           speechkit.ModeDictation,
			Name:           "Nova-3 Diarization (Deepgram)",
			ProviderKind:   speechkit.ProviderKindDirectProvider,
			ExecutionMode:  speechkit.ExecutionModeDeepgram,
			ModelID:        "nova-3",
			Source:         "Deepgram",
			Description:    "Deepgram-hosted transcription with diarize_model=latest for batch speaker labels and word-level speaker confidence.",
			License:        "proprietary",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilitySpeakerDiarization},
			AdapterKind:    "deepgram_stt",
			AllowInference: true,
			Recommended:    true,
		},
		{
			ID:             "stt.assemblyai.universal",
			Mode:           speechkit.ModeDictation,
			Name:           "Universal-3.5 Pro (AssemblyAI)",
			ProviderKind:   speechkit.ProviderKindDirectProvider,
			ExecutionMode:  speechkit.ExecutionModeAssemblyAI,
			ModelID:        "universal-3-5-pro,universal-2",
			Source:         "AssemblyAI",
			Description:    "AssemblyAI Universal-3.5 Pro. Short clips ride the synchronous endpoint (finished transcript in one request, ~134 ms p50) with prompt steering, keyterms, and conversation context; longer or feature-rich requests use the async flow, and realtime dictation streams over v3 with agent context. The diarization variant adds speaker labels and content-based speaker identification by name/role.",
			License:        "proprietary",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryPrompt, speechkit.CapabilityNativeContextPrompt, speechkit.CapabilityNativeDictationStream},
			AdapterKind:    "assemblyai_stt",
			AllowInference: true,
			Recommended:    true,
		},
		{
			ID:             "stt.assemblyai.universal-diarization",
			Mode:           speechkit.ModeDictation,
			Name:           "Universal-3.5 Pro Diarization + Speaker Identification (AssemblyAI)",
			ProviderKind:   speechkit.ProviderKindDirectProvider,
			ExecutionMode:  speechkit.ExecutionModeAssemblyAI,
			ModelID:        "universal-3-5-pro,universal-2",
			Source:         "AssemblyAI",
			Description:    "AssemblyAI pre-recorded transcription with speaker_labels and optional content-based speaker identification by known names or roles. Diarization requests always use the async flow (the sync endpoint does not diarize).",
			License:        "proprietary",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilitySpeakerDiarization, speechkit.CapabilitySpeakerIdentification, speechkit.CapabilitySpeakerAttribution},
			AdapterKind:    "assemblyai_stt",
			AllowInference: true,
			Recommended:    true,
		},
		{
			ID:            "stt.groq.whisper-large-v3-turbo",
			Mode:          speechkit.ModeDictation,
			Name:          "Whisper Large v3 Turbo (Groq)",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeGroq,
			ModelID:       ModelGroqWhisperLargeV3Turbo,
			Source:        "Groq",
			Description:   "Fast direct API transcription profile for low-latency dictation fallbacks.",
			License:       "proprietary",
			Capabilities:  []speechkit.Capability{speechkit.CapabilityTranscription, speechkit.CapabilitySTT, speechkit.CapabilityAudioInput, speechkit.CapabilityDictionaryPrompt},
			AdapterKind:   "stt_router",
			EvidenceURL:   "https://console.groq.com/docs/speech-to-text",
			Variants: []speechkit.ModelVariant{
				{ID: "groq.whisper-large-v3-turbo", Name: "Whisper Large v3 Turbo", ModelID: ModelGroqWhisperLargeV3Turbo, Recommended: true},
				{ID: "groq.whisper-large-v3", Name: "Whisper Large v3", ModelID: ModelGroqWhisperLargeV3, Description: "Higher-accuracy Groq STT option for hosts that prefer quality over the turbo profile."},
			},
			AllowInference: true,
			Recommended:    true,
		},
	}
}
