package catalog

import (
	"github.com/kombifyio/SpeechKit/pkg/speechkit"
)

// voiceAgentProviderProfiles returns the built-in Voice Agent (realtime)
// section of the default provider catalog.
func voiceAgentProviderProfiles() []speechkit.ProviderProfile {
	return []speechkit.ProviderProfile{
		{
			ID:            "realtime.builtin.pipeline",
			Mode:          speechkit.ModeVoiceAgent,
			Name:          "SpeechKit Local Voice Pipeline",
			ProviderKind:  speechkit.ProviderKindLocalBuiltIn,
			ExecutionMode: speechkit.ExecutionModeLocal,
			ModelID:       "speechkit-local-voice-pipeline",
			Source:        "Local Built-in",
			Description:   "Voice Agent pipeline fallback using local transcription, SpeechKit-managed llama.cpp dialogue, and a TTS path.",
			License:       "mixed",
			Capabilities:  []speechkit.Capability{speechkit.CapabilityAudioInput, speechkit.CapabilityPipelineFallback, speechkit.CapabilitySessionSummary},
			AdapterKind:   "voice_pipeline",
			Variants: []speechkit.ModelVariant{
				{ID: "llamacpp.gemma-4-e2b-it-q8-0-voice", Name: "Gemma 4 E2B IT Q8_0", ModelID: "gemma-4-E2B-it-Q8_0.gguf", Description: "Default lightweight GGUF model for local Voice Agent pipeline fallback.", Recommended: true},
				{ID: "llamacpp.gemma-4-e4b-it-q4-k-m-voice", Name: "Gemma 4 E4B IT Q4_K_M", ModelID: "google_gemma-4-E4B-it-Q4_K_M.gguf", Description: "Stronger optional GGUF model for Voice Agent pipeline fallback."},
			},
			AllowInference: true,
			Default:        true,
			Recommended:    true,
			Experimental:   true,
		},
		{
			ID:             "realtime.ollama.gemma4-e4b-pipeline",
			Mode:           speechkit.ModeVoiceAgent,
			Name:           "Gemma 4 E4B Voice Pipeline (Ollama)",
			ProviderKind:   speechkit.ProviderKindLocalProvider,
			ExecutionMode:  speechkit.ExecutionModeOllama,
			ModelID:        "gemma4:e4b",
			Source:         "Local Provider",
			Description:    "Voice Agent pipeline fallback with Ollama as the dialogue model.",
			License:        "gemma",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityAudioInput, speechkit.CapabilityPipelineFallback, speechkit.CapabilitySessionSummary},
			AdapterKind:    "voice_pipeline",
			AllowInference: true,
			Experimental:   true,
		},
		{
			ID:             "realtime.hf.qwen38-27b",
			Mode:           speechkit.ModeVoiceAgent,
			Name:           "Qwen 3.8 27B Voice Fallback (Hugging Face)",
			ProviderKind:   speechkit.ProviderKindCloudProvider,
			ExecutionMode:  speechkit.ExecutionModeHFRouted,
			ModelID:        modelHFQwen38,
			Source:         "Hugging Face",
			Description:    "Voice Agent fallback over Hugging Face. SpeechKit uses the capture pipeline when Gemini Live is unavailable or not selected.",
			License:        "apache-2.0",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityAudioInput, speechkit.CapabilityPipelineFallback, speechkit.CapabilitySessionSummary},
			AdapterKind:    "voice_pipeline",
			AllowInference: true,
			Recommended:    true,
			Experimental:   true,
		},
		{
			ID:             "realtime.openrouter.gemini-3.5-flash-pipeline",
			Mode:           speechkit.ModeVoiceAgent,
			Name:           "Gemini 3.5 Flash Voice Pipeline (OpenRouter)",
			ProviderKind:   speechkit.ProviderKindCloudProvider,
			ExecutionMode:  speechkit.ExecutionModeOpenRouter,
			ModelID:        modelOpenRouterGemini35Flash,
			Source:         "OpenRouter",
			Description:    "Voice Agent pipeline fallback with OpenRouter as the dialogue model.",
			License:        "proprietary",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityAudioInput, speechkit.CapabilityPipelineFallback, speechkit.CapabilitySessionSummary},
			AdapterKind:    "voice_pipeline",
			AllowInference: true,
			Experimental:   true,
		},
		{
			ID:            "realtime.google.gemini-native-audio",
			Mode:          speechkit.ModeVoiceAgent,
			Name:          "Gemini Live Native Audio",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeGoogle,
			Provider:      "google",
			ModelID:       modelGemini38Live,
			Lifecycle:     speechkit.ModelLifecycleGA,
			Source:        "Google",
			Description:   "Opt-in native real-time voice conversation over the Google Live API with your own GOOGLE_AI_API_KEY. Gemini 3.8 Live (GA) is the primary model and reasons on its own, so a reasoning effort is not sent to it; the Extended Thinking preview adds background reasoning and runs tools non-blocking. Never a default.",
			License:       "proprietary",
			Capabilities: []speechkit.Capability{
				speechkit.CapabilityAudioInput,
				speechkit.CapabilityRealtimeAudio,
				speechkit.CapabilityToolCalling,
				speechkit.CapabilityNativeContextPrompt,
				speechkit.CapabilityReasoningEffort,
				speechkit.CapabilitySessionResume,
				speechkit.CapabilityTranscript,
				speechkit.CapabilityInterruptions,
				speechkit.CapabilitySessionSummary,
			},
			SupportedLocales: []string{"*"},
			NativeOptions:    []string{"context_prompt", "reasoning_effort"},
			AuthRequirement:  "api_key",
			Transport:        "websocket",
			EvidenceURL:      "https://ai.google.dev/gemini-api/docs/live-guide",
			AdapterKind:      "gemini_live",
			Variants: []speechkit.ModelVariant{
				{ID: "gemini.3.8.live", Name: "Gemini 3.8 Live", ModelID: modelGemini38Live, Recommended: true},
				{ID: "gemini.3.8.live-extended-thinking", Name: "Gemini 3.8 Live Extended Thinking (Preview)", ModelID: modelGemini38LiveExtendedThinking, Description: "Background reasoning with conversational fillers; tools always run non-blocking."},
			},
			AllowInference: true,
		},
		{
			ID:            "realtime.google.gemini-live-translate",
			Mode:          speechkit.ModeVoiceAgent,
			Name:          "Gemini 3.5 Live Translate",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeGoogle,
			Provider:      "google",
			ModelID:       modelGemini35LiveTranslatePreview,
			Lifecycle:     speechkit.ModelLifecyclePreview,
			Source:        "Google",
			Description:   "Opt-in Live API speech-to-speech translation profile with your own GOOGLE_AI_API_KEY. It is deliberately separate from the general Gemini Live dialogue profile so Gemini Live selections do not point at a translation-only model.",
			License:       "proprietary",
			Capabilities: []speechkit.Capability{
				speechkit.CapabilityAudioInput,
				speechkit.CapabilityRealtimeAudio,
				speechkit.CapabilityTranslation,
				speechkit.CapabilityTranscript,
				speechkit.CapabilityInterruptions,
				speechkit.CapabilitySessionSummary,
			},
			SupportedLocales: []string{"*"},
			NativeOptions:    []string{"translation", "turn_detection"},
			AuthRequirement:  "api_key",
			Transport:        "websocket",
			EvidenceURL:      "https://ai.google.dev/gemini-api/docs/models/gemini-3.5-live-translate-preview",
			AdapterKind:      "gemini_live_translate",
			Variants: []speechkit.ModelVariant{
				{ID: "gemini.3.5.live-translate-preview", Name: "Gemini 3.5 Live Translate Preview", ModelID: modelGemini35LiveTranslatePreview, Recommended: true},
			},
			AllowInference: true,
			Experimental:   true,
		},
		{
			ID:            "realtime.deepgram.voice-agent",
			Mode:          speechkit.ModeVoiceAgent,
			Name:          "Deepgram Voice Agent (Flux)",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeDeepgram,
			Provider:      "deepgram",
			ModelID:       modelDeepgramFluxGeneralMulti + "+aura-2",
			Lifecycle:     speechkit.ModelLifecycleGA,
			Source:        "Deepgram",
			Description:   "Deepgram Voice Agent API — native audio-to-audio dialogue (Flux listen with turn events, configurable think LLM, Aura-2 speak) over a single WebSocket. Flux TTS is selectable for English-pinned sessions. Nova-3 remains the general dictation/diarization baseline.",
			License:       "proprietary",
			Capabilities: []speechkit.Capability{
				speechkit.CapabilityAudioInput,
				speechkit.CapabilityRealtimeAudio,
				speechkit.CapabilityToolCalling,
				speechkit.CapabilityWordsNativeHints,
				speechkit.CapabilityNativeContextPrompt,
				speechkit.CapabilityNativeKeyterms,
				speechkit.CapabilityLanguageHints,
				speechkit.CapabilitySpeakerStreaming,
				speechkit.CapabilityTranscript,
				speechkit.CapabilityInterruptions,
				speechkit.CapabilitySessionSummary,
			},
			SupportedLocales: []string{"en", "de", "es", "fr", "hi", "it", "ja", "nl", "pt", "ru"},
			NativeOptions:    []string{"context_prompt", "language_hints", "keyterms", "turn_detection"},
			AuthRequirement:  "api_key",
			Transport:        "websocket",
			EvidenceURL:      "https://developers.deepgram.com/docs/voice-agent-settings",
			AdapterKind:      "deepgram_voice_agent",
			Variants: []speechkit.ModelVariant{
				{ID: "deepgram.flux-general-multi", Name: "Flux General Multilingual", ModelID: modelDeepgramFluxGeneralMulti, Recommended: true},
				{ID: "deepgram.flux-general-en", Name: "Flux General English", ModelID: modelDeepgramFluxGeneralEN},
				{ID: "deepgram.flux-general-en-flux-tts", Name: "Flux General English + Flux TTS", ModelID: modelDeepgramFluxGeneralEN + "+" + modelDeepgramFluxTTSDefaultEN},
				{ID: "deepgram.nova-3-legacy-agent-listen", Name: "Nova-3 Listen (legacy)", ModelID: modelDeepgramNova3},
			},
			AllowInference: true,
			Recommended:    true,
		},
		{
			ID:            "realtime.assemblyai.voice-agent",
			Mode:          speechkit.ModeVoiceAgent,
			Name:          "AssemblyAI Voice Agent",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeAssemblyAI,
			Provider:      "assemblyai",
			ModelID:       modelAssemblyAIVoiceAgent,
			Lifecycle:     speechkit.ModelLifecycleGA,
			Source:        "AssemblyAI",
			Description:   "AssemblyAI Voice Agent API over wss://agents.assemblyai.com/v1/ws with native session.update, session.ready, input.audio, reply.audio, transcripts, tools, and clean session.end teardown.",
			License:       "proprietary",
			Capabilities: []speechkit.Capability{
				speechkit.CapabilityAudioInput,
				speechkit.CapabilityRealtimeAudio,
				speechkit.CapabilityToolCalling,
				speechkit.CapabilityWordsNativeHints,
				speechkit.CapabilityNativeContextPrompt,
				speechkit.CapabilityNativeKeyterms,
				speechkit.CapabilitySessionResume,
				speechkit.CapabilitySpeakerStreaming,
				speechkit.CapabilityTranscript,
				speechkit.CapabilityInterruptions,
				speechkit.CapabilitySessionSummary,
			},
			SupportedLocales: []string{"en", "es", "de", "fr", "pt", "it", "tr", "nl", "sv", "no", "da", "fi", "hi", "vi", "ar", "he", "ja", "zh"},
			NativeOptions:    []string{"context_prompt", "keyterms", "resume"},
			AuthRequirement:  "api_key",
			Transport:        "websocket",
			EvidenceURL:      "https://www.assemblyai.com/docs/voice-agents/voice-agent-api",
			AdapterKind:      "assemblyai_voice_agent",
			AllowInference:   true,
			Recommended:      true,
		},
		{
			ID:            "realtime.openai.gpt-realtime-2",
			Mode:          speechkit.ModeVoiceAgent,
			Name:          "OpenAI Realtime",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeOpenAI,
			Provider:      "openai",
			ModelID:       modelOpenAIRealtime21,
			Lifecycle:     speechkit.ModelLifecycleGA,
			Source:        "OpenAI",
			Description:   "OpenAI Realtime native audio session for apps that want the same LiveProvider contract with OpenAI's realtime model. The profile id keeps its historical name; the model is gpt-realtime-2.1.",
			License:       "proprietary",
			Capabilities: []speechkit.Capability{
				speechkit.CapabilityAudioInput,
				speechkit.CapabilityRealtimeAudio,
				speechkit.CapabilityToolCalling,
				speechkit.CapabilityNativeContextPrompt,
				speechkit.CapabilityReasoningEffort,
				speechkit.CapabilityTranslation,
				speechkit.CapabilityTranscriptionOnly,
				speechkit.CapabilityTranscript,
				speechkit.CapabilityInterruptions,
				speechkit.CapabilitySessionSummary,
			},
			SupportedLocales: []string{"*"},
			NativeOptions:    []string{"context_prompt", "reasoning_effort", "turn_detection", "transcription_only", "translation"},
			AuthRequirement:  "api_key",
			Transport:        "websocket",
			EvidenceURL:      "https://developers.openai.com/api/docs/models/gpt-realtime-2.1",
			AdapterKind:      "openai_realtime",
			Variants: []speechkit.ModelVariant{
				{ID: "openai.gpt-realtime-2.1", Name: "GPT Realtime 2.1", ModelID: modelOpenAIRealtime21, Recommended: true},
				{ID: "openai.gpt-realtime-2.1-mini", Name: "GPT Realtime 2.1 mini", ModelID: modelOpenAIRealtime21Mini, Description: "Lower cost realtime model."},
			},
			AllowInference: true,
			Recommended:    true,
		},
		{
			// GPT-Live runs its own /v1/live/sessions protocol and hands
			// reasoning and tools to a backend Responses model; SpeechKit uses
			// the configured OpenAI agent model as that backend.
			ID:            "realtime.openai.gpt-live-1",
			Mode:          speechkit.ModeVoiceAgent,
			Name:          "OpenAI GPT-Live",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeOpenAI,
			Provider:      "gpt-live",
			ModelID:       modelOpenAIGPTLive1,
			Lifecycle:     speechkit.ModelLifecyclePreview,
			Source:        "OpenAI",
			Description:   "OpenAI's full-duplex GPT-Live voice (12 new voices) that delegates reasoning and tools to a backend model — SpeechKit sends the configured OpenAI agent model. Early adapter: the protocol reports no barge-in or turn-end event yet, so the kernel settles turns on its timer.",
			License:       "proprietary",
			Capabilities: []speechkit.Capability{
				speechkit.CapabilityAudioInput,
				speechkit.CapabilityRealtimeAudio,
				speechkit.CapabilityToolCalling,
				speechkit.CapabilityTranscript,
				speechkit.CapabilitySessionSummary,
			},
			SupportedLocales: []string{"*"},
			AuthRequirement:  "api_key",
			Transport:        "websocket",
			EvidenceURL:      "https://developers.openai.com/api/docs/models/gpt-live-1",
			AdapterKind:      "openai_live",
			AllowInference:   true,
			Experimental:     true,
		},
		{
			ID:            "realtime.foundry.gpt-realtime-2",
			Mode:          speechkit.ModeVoiceAgent,
			Name:          "Microsoft Foundry Realtime",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeFoundry,
			Provider:      "foundry",
			ModelID:       modelOpenAIRealtime21,
			Lifecycle:     speechkit.ModelLifecycleGA,
			Source:        "Microsoft Foundry",
			Description:   "Azure-hosted OpenAI Realtime session over the Microsoft Foundry v1 websocket surface. The model id is the default deployment name — override it with your own deployment name in the Foundry integration settings. Existing gpt-realtime-2 deployments keep working: Azure upgrades them to gpt-realtime-2.1.",
			License:       "proprietary",
			Capabilities: []speechkit.Capability{
				speechkit.CapabilityAudioInput,
				speechkit.CapabilityRealtimeAudio,
				speechkit.CapabilityToolCalling,
				speechkit.CapabilityNativeContextPrompt,
				speechkit.CapabilityReasoningEffort,
				speechkit.CapabilityTranslation,
				speechkit.CapabilityTranscriptionOnly,
				speechkit.CapabilityTranscript,
				speechkit.CapabilityInterruptions,
				speechkit.CapabilitySessionSummary,
			},
			SupportedLocales: []string{"*"},
			NativeOptions:    []string{"context_prompt", "reasoning_effort", "turn_detection", "transcription_only", "translation"},
			AuthRequirement:  "api_key",
			Transport:        "websocket",
			EvidenceURL:      "https://learn.microsoft.com/azure/ai-foundry/openai/realtime-audio-quickstart",
			AdapterKind:      "foundry_realtime",
			Variants: []speechkit.ModelVariant{
				{ID: "foundry.gpt-realtime-2.1", Name: "GPT Realtime 2.1", ModelID: modelOpenAIRealtime21, Recommended: true},
				{ID: "foundry.gpt-realtime-2.1-mini", Name: "GPT Realtime 2.1 mini", ModelID: modelOpenAIRealtime21Mini, Description: "Lower cost realtime deployment."},
			},
			AllowInference: true,
			Recommended:    true,
		},
		{
			// Voice Live is Microsoft's managed voice agent on the same Foundry
			// resource: the brain is any of the models the service hosts (no
			// deployment needed), speech in comes from MAI-Transcribe, speech
			// out from a MAI-Voice-2 voice, with Azure semantic VAD, noise
			// suppression and echo cancellation on the server. The model id is
			// the brain; voice and transcription live in the Foundry settings.
			ID:            "realtime.foundry.voice-live",
			Mode:          speechkit.ModeVoiceAgent,
			Name:          "Microsoft Foundry Voice Live",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeFoundry,
			Provider:      "foundry-voicelive",
			ModelID:       modelOpenAIRealtime21,
			Lifecycle:     speechkit.ModelLifecycleGA,
			Source:        "Microsoft Foundry",
			Description:   "Microsoft-native realtime voice agent: Voice Live pairs a hosted brain model with MAI-Voice-2 speech output and MAI-Transcribe-2 input transcription, plus server-side semantic turn detection and noise suppression. The MAI voice and transcription models are public preview.",
			License:       "proprietary",
			Capabilities: []speechkit.Capability{
				speechkit.CapabilityAudioInput,
				speechkit.CapabilityRealtimeAudio,
				speechkit.CapabilityToolCalling,
				speechkit.CapabilityNativeContextPrompt,
				speechkit.CapabilityTranscript,
				speechkit.CapabilityInterruptions,
				speechkit.CapabilitySessionSummary,
			},
			SupportedLocales: []string{"*"},
			NativeOptions:    []string{"context_prompt", "turn_detection"},
			AuthRequirement:  "api_key",
			Transport:        "websocket",
			EvidenceURL:      "https://learn.microsoft.com/azure/ai-services/speech-service/voice-live",
			AdapterKind:      "foundry_voicelive",
			Variants: []speechkit.ModelVariant{
				{ID: "foundry.voicelive.gpt-realtime-2.1", Name: "GPT Realtime 2.1 brain", ModelID: modelOpenAIRealtime21, Recommended: true},
				{ID: "foundry.voicelive.gpt-realtime-2.1-mini", Name: "GPT Realtime 2.1 mini brain", ModelID: modelOpenAIRealtime21Mini, Description: "Lower cost realtime brain (Voice Live Standard)."},
				{ID: "foundry.voicelive.gpt-5.6-terra", Name: "GPT-5.6 Terra brain", ModelID: modelFoundryVoiceLiveGPT56Terra, Description: "Newest text brain the Voice Live service hosts itself; speech in and out come from the service."},
				{ID: "foundry.voicelive.gpt-5.6-luna", Name: "GPT-5.6 Luna brain", ModelID: modelFoundryVoiceLiveGPT56Luna, Description: "Fast, low-cost text brain (Voice Live Standard)."},
				{ID: "foundry.voicelive.azure-realtime", Name: "Azure Realtime brain", ModelID: modelFoundryVoiceLiveAzureRealtime, Description: "Microsoft's own speech-to-speech model with its dedicated native voices."},
				{ID: "foundry.voicelive.phi4-mm-realtime", Name: "Phi-4 multimodal realtime brain (Preview)", ModelID: modelFoundryVoiceLivePhi4MM, Description: "Small Microsoft model for low-latency agents."},
			},
			AllowInference: true,
			Recommended:    true,
		},
		{
			// GPT-Live on Foundry is the same /live/sessions protocol served
			// from the resource host (/openai/v1/live/sessions). The model id
			// is the default deployment name; the delegated backend is the
			// configured Foundry agent deployment.
			ID:            "realtime.foundry.gpt-live-1",
			Mode:          speechkit.ModeVoiceAgent,
			Name:          "Microsoft Foundry GPT-Live",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeFoundry,
			Provider:      "foundry-gpt-live",
			ModelID:       modelOpenAIGPTLive1,
			Lifecycle:     speechkit.ModelLifecyclePreview,
			Source:        "Microsoft Foundry",
			Description:   "OpenAI's full-duplex GPT-Live voice served by your Microsoft Foundry resource. The model id is the default deployment name — override it with your own GPT-Live deployment name in the Foundry integration settings. Reasoning and tools run in the configured Foundry agent deployment, which GPT-Live delegates to.",
			License:       "proprietary",
			Capabilities: []speechkit.Capability{
				speechkit.CapabilityAudioInput,
				speechkit.CapabilityRealtimeAudio,
				speechkit.CapabilityToolCalling,
				speechkit.CapabilityTranscript,
				speechkit.CapabilitySessionSummary,
			},
			SupportedLocales: []string{"*"},
			AuthRequirement:  "api_key",
			Transport:        "websocket",
			EvidenceURL:      "https://learn.microsoft.com/azure/foundry/openai/how-to/gpt-live",
			AdapterKind:      "foundry_gpt_live",
			AllowInference:   true,
			Experimental:     true,
		},
	}
}
