package catalog

import (
	"github.com/kombifyio/SpeechKit/pkg/speechkit"
)

// voiceAgentProviderProfiles returns the built-in Voice Agent (realtime)
// section of the default provider catalog.
func voiceAgentProviderProfiles() []speechkit.ProviderProfile {
	return []speechkit.ProviderProfile{
		{
			ID:            "realtime.builtin.pipeline",
			Mode:          speechkit.ModeVoiceAgent,
			Name:          "SpeechKit Local Voice Pipeline",
			ProviderKind:  speechkit.ProviderKindLocalBuiltIn,
			ExecutionMode: speechkit.ExecutionModeLocal,
			ModelID:       "speechkit-local-voice-pipeline",
			Source:        "Local Built-in",
			Description:   "Voice Agent pipeline fallback using local transcription, SpeechKit-managed llama.cpp dialogue, and a TTS path.",
			License:       "mixed",
			Capabilities:  []speechkit.Capability{speechkit.CapabilityAudioInput, speechkit.CapabilityPipelineFallback, speechkit.CapabilitySessionSummary},
			AdapterKind:   "voice_pipeline",
			Variants: []speechkit.ModelVariant{
				{ID: "llamacpp.gemma-4-e2b-it-q8-0-voice", Name: "Gemma 4 E2B IT Q8_0", ModelID: "gemma-4-E2B-it-Q8_0.gguf", Description: "Default lightweight GGUF model for local Voice Agent pipeline fallback.", Recommended: true},
				{ID: "llamacpp.gemma-4-e4b-it-q4-k-m-voice", Name: "Gemma 4 E4B IT Q4_K_M", ModelID: "gemma-4-E4B-it-Q4_K_M.gguf", Description: "Stronger optional GGUF model for Voice Agent pipeline fallback."},
			},
			AllowInference: true,
			Default:        true,
			Recommended:    true,
			Experimental:   true,
		},
		{
			ID:             "realtime.ollama.gemma4-e4b-pipeline",
			Mode:           speechkit.ModeVoiceAgent,
			Name:           "Gemma 4 E4B Voice Pipeline (Ollama)",
			ProviderKind:   speechkit.ProviderKindLocalProvider,
			ExecutionMode:  speechkit.ExecutionModeOllama,
			ModelID:        "gemma4:e4b",
			Source:         "Local Provider",
			Description:    "Voice Agent pipeline fallback with Ollama as the dialogue model.",
			License:        "gemma",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityAudioInput, speechkit.CapabilityPipelineFallback, speechkit.CapabilitySessionSummary},
			AdapterKind:    "voice_pipeline",
			AllowInference: true,
			Experimental:   true,
		},
		{
			ID:             "realtime.hf.qwen35-27b",
			Mode:           speechkit.ModeVoiceAgent,
			Name:           "Qwen 3.5 27B Voice Fallback (Hugging Face)",
			ProviderKind:   speechkit.ProviderKindCloudProvider,
			ExecutionMode:  speechkit.ExecutionModeHFRouted,
			ModelID:        "Qwen/Qwen3.5-27B",
			Source:         "Hugging Face",
			Description:    "Voice Agent fallback over Hugging Face. SpeechKit uses the capture pipeline when Gemini Live is unavailable or not selected.",
			License:        "apache-2.0",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityAudioInput, speechkit.CapabilityPipelineFallback, speechkit.CapabilitySessionSummary},
			AdapterKind:    "voice_pipeline",
			AllowInference: true,
			Recommended:    true,
			Experimental:   true,
		},
		{
			ID:             "realtime.openrouter.gemini-2.5-flash-pipeline",
			Mode:           speechkit.ModeVoiceAgent,
			Name:           "Gemini 2.5 Flash Voice Pipeline (OpenRouter)",
			ProviderKind:   speechkit.ProviderKindCloudProvider,
			ExecutionMode:  speechkit.ExecutionModeOpenRouter,
			ModelID:        "google/gemini-2.5-flash",
			Source:         "OpenRouter",
			Description:    "Voice Agent pipeline fallback with OpenRouter as the dialogue model.",
			License:        "proprietary",
			Capabilities:   []speechkit.Capability{speechkit.CapabilityAudioInput, speechkit.CapabilityPipelineFallback, speechkit.CapabilitySessionSummary},
			AdapterKind:    "voice_pipeline",
			AllowInference: true,
			Experimental:   true,
		},
		{
			ID:            "realtime.google.gemini-native-audio",
			Mode:          speechkit.ModeVoiceAgent,
			Name:          "Gemini Live Native Audio",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeGoogle,
			Provider:      "google",
			ModelID:       ModelGemini31FlashLivePreview,
			Lifecycle:     speechkit.ModelLifecyclePreview,
			Source:        "Google",
			Description:   "Opt-in native real-time voice conversation over the Google Live API with your own GOOGLE_AI_API_KEY. Gemini 3.1 Flash Live is the primary preview; Gemini 2.5 Flash Native Audio remains the same-provider fallback. Never a default.",
			License:       "proprietary",
			Capabilities: []speechkit.Capability{
				speechkit.CapabilityAudioInput,
				speechkit.CapabilityRealtimeAudio,
				speechkit.CapabilityToolCalling,
				speechkit.CapabilityNativeContextPrompt,
				speechkit.CapabilityReasoningEffort,
				speechkit.CapabilitySessionResume,
				speechkit.CapabilityTranscript,
				speechkit.CapabilityInterruptions,
				speechkit.CapabilitySessionSummary,
			},
			SupportedLocales: []string{"*"},
			NativeOptions:    []string{"context_prompt", "reasoning_effort"},
			AuthRequirement:  "api_key",
			Transport:        "websocket",
			EvidenceURL:      "https://ai.google.dev/gemini-api/docs/live-guide",
			AdapterKind:      "gemini_live",
			Variants: []speechkit.ModelVariant{
				{ID: "gemini.3.1.flash-live-preview", Name: "Gemini 3.1 Flash Live Preview", ModelID: ModelGemini31FlashLivePreview, Recommended: true},
				{ID: "gemini.2.5.flash-native-audio-preview", Name: "Gemini 2.5 Flash Native Audio Preview", ModelID: ModelGemini25FlashNativeAudioPreview},
			},
			AllowInference: true,
		},
		{
			ID:            "realtime.google.gemini-live-translate",
			Mode:          speechkit.ModeVoiceAgent,
			Name:          "Gemini 3.5 Live Translate",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeGoogle,
			Provider:      "google",
			ModelID:       ModelGemini35LiveTranslatePreview,
			Lifecycle:     speechkit.ModelLifecyclePreview,
			Source:        "Google",
			Description:   "Opt-in Live API speech-to-speech translation profile with your own GOOGLE_AI_API_KEY. It is deliberately separate from the general Gemini Live dialogue profile so Gemini Live selections do not point at a translation-only model.",
			License:       "proprietary",
			Capabilities: []speechkit.Capability{
				speechkit.CapabilityAudioInput,
				speechkit.CapabilityRealtimeAudio,
				speechkit.CapabilityTranslation,
				speechkit.CapabilityTranscript,
				speechkit.CapabilityInterruptions,
				speechkit.CapabilitySessionSummary,
			},
			SupportedLocales: []string{"*"},
			NativeOptions:    []string{"translation", "turn_detection"},
			AuthRequirement:  "api_key",
			Transport:        "websocket",
			EvidenceURL:      "https://ai.google.dev/gemini-api/docs/models/gemini-3.5-live-translate-preview",
			AdapterKind:      "gemini_live_translate",
			Variants: []speechkit.ModelVariant{
				{ID: "gemini.3.5.live-translate-preview", Name: "Gemini 3.5 Live Translate Preview", ModelID: ModelGemini35LiveTranslatePreview, Recommended: true},
			},
			AllowInference: true,
			Experimental:   true,
		},
		{
			ID:            "realtime.deepgram.voice-agent",
			Mode:          speechkit.ModeVoiceAgent,
			Name:          "Deepgram Voice Agent (Flux)",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeDeepgram,
			Provider:      "deepgram",
			ModelID:       ModelDeepgramFluxGeneralMulti + "+aura-2",
			Lifecycle:     speechkit.ModelLifecycleGA,
			Source:        "Deepgram",
			Description:   "Deepgram Voice Agent API — native audio-to-audio dialogue (Flux listen with turn events, configurable think LLM, Aura-2 speak) over a single WebSocket. Flux TTS is selectable for English-pinned sessions. Nova-3 remains the general dictation/diarization baseline.",
			License:       "proprietary",
			Capabilities: []speechkit.Capability{
				speechkit.CapabilityAudioInput,
				speechkit.CapabilityRealtimeAudio,
				speechkit.CapabilityToolCalling,
				speechkit.CapabilityWordsNativeHints,
				speechkit.CapabilityNativeContextPrompt,
				speechkit.CapabilityNativeKeyterms,
				speechkit.CapabilityLanguageHints,
				speechkit.CapabilitySpeakerStreaming,
				speechkit.CapabilityTranscript,
				speechkit.CapabilityInterruptions,
				speechkit.CapabilitySessionSummary,
			},
			SupportedLocales: []string{"en", "de", "es", "fr", "hi", "it", "ja", "nl", "pt", "ru"},
			NativeOptions:    []string{"context_prompt", "language_hints", "keyterms", "turn_detection"},
			AuthRequirement:  "api_key",
			Transport:        "websocket",
			EvidenceURL:      "https://developers.deepgram.com/docs/voice-agent-settings",
			AdapterKind:      "deepgram_voice_agent",
			Variants: []speechkit.ModelVariant{
				{ID: "deepgram.flux-general-multi", Name: "Flux General Multilingual", ModelID: ModelDeepgramFluxGeneralMulti, Recommended: true},
				{ID: "deepgram.flux-general-en", Name: "Flux General English", ModelID: ModelDeepgramFluxGeneralEN},
				{ID: "deepgram.flux-general-en-flux-tts", Name: "Flux General English + Flux TTS", ModelID: ModelDeepgramFluxGeneralEN + "+" + ModelDeepgramFluxTTSDefaultEN},
				{ID: "deepgram.nova-3-legacy-agent-listen", Name: "Nova-3 Listen (legacy)", ModelID: ModelDeepgramNova3},
			},
			AllowInference: true,
			Recommended:    true,
		},
		{
			ID:            "realtime.assemblyai.voice-agent",
			Mode:          speechkit.ModeVoiceAgent,
			Name:          "AssemblyAI Voice Agent",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeAssemblyAI,
			Provider:      "assemblyai",
			ModelID:       ModelAssemblyAIVoiceAgent,
			Lifecycle:     speechkit.ModelLifecycleGA,
			Source:        "AssemblyAI",
			Description:   "AssemblyAI Voice Agent API over wss://agents.assemblyai.com/v1/ws with native session.update, session.ready, input.audio, reply.audio, transcripts, tools, and clean session.end teardown.",
			License:       "proprietary",
			Capabilities: []speechkit.Capability{
				speechkit.CapabilityAudioInput,
				speechkit.CapabilityRealtimeAudio,
				speechkit.CapabilityToolCalling,
				speechkit.CapabilityWordsNativeHints,
				speechkit.CapabilityNativeContextPrompt,
				speechkit.CapabilityNativeKeyterms,
				speechkit.CapabilitySessionResume,
				speechkit.CapabilitySpeakerStreaming,
				speechkit.CapabilityTranscript,
				speechkit.CapabilityInterruptions,
				speechkit.CapabilitySessionSummary,
			},
			SupportedLocales: []string{"en", "es", "de", "fr", "pt", "it", "tr", "nl", "sv", "no", "da", "fi", "hi", "vi", "ar", "he", "ja", "zh"},
			NativeOptions:    []string{"context_prompt", "keyterms", "resume"},
			AuthRequirement:  "api_key",
			Transport:        "websocket",
			EvidenceURL:      "https://www.assemblyai.com/docs/voice-agents/voice-agent-api",
			AdapterKind:      "assemblyai_voice_agent",
			AllowInference:   true,
			Recommended:      true,
		},
		{
			ID:            "realtime.openai.gpt-realtime-2",
			Mode:          speechkit.ModeVoiceAgent,
			Name:          "OpenAI Realtime",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeOpenAI,
			Provider:      "openai",
			ModelID:       ModelOpenAIRealtime2,
			Lifecycle:     speechkit.ModelLifecycleGA,
			Source:        "OpenAI",
			Description:   "OpenAI Realtime native audio session for apps that want the same LiveProvider contract with OpenAI's realtime model.",
			License:       "proprietary",
			Capabilities: []speechkit.Capability{
				speechkit.CapabilityAudioInput,
				speechkit.CapabilityRealtimeAudio,
				speechkit.CapabilityToolCalling,
				speechkit.CapabilityNativeContextPrompt,
				speechkit.CapabilityReasoningEffort,
				speechkit.CapabilityTranslation,
				speechkit.CapabilityTranscriptionOnly,
				speechkit.CapabilityTranscript,
				speechkit.CapabilityInterruptions,
				speechkit.CapabilitySessionSummary,
			},
			SupportedLocales: []string{"*"},
			NativeOptions:    []string{"context_prompt", "reasoning_effort", "turn_detection", "transcription_only", "translation"},
			AuthRequirement:  "api_key",
			Transport:        "websocket",
			EvidenceURL:      "https://platform.openai.com/docs/guides/realtime",
			AdapterKind:      "openai_realtime",
			AllowInference:   true,
			Recommended:      true,
		},
		{
			ID:            "realtime.foundry.gpt-realtime-2",
			Mode:          speechkit.ModeVoiceAgent,
			Name:          "Microsoft Foundry Realtime",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeFoundry,
			Provider:      "foundry",
			ModelID:       ModelOpenAIRealtime2,
			Lifecycle:     speechkit.ModelLifecycleGA,
			Source:        "Microsoft Foundry",
			Description:   "Azure-hosted OpenAI Realtime session over the Microsoft Foundry v1 websocket surface. The model id is the default deployment name — override it with your own deployment name in the Foundry integration settings.",
			License:       "proprietary",
			Capabilities: []speechkit.Capability{
				speechkit.CapabilityAudioInput,
				speechkit.CapabilityRealtimeAudio,
				speechkit.CapabilityToolCalling,
				speechkit.CapabilityNativeContextPrompt,
				speechkit.CapabilityReasoningEffort,
				speechkit.CapabilityTranslation,
				speechkit.CapabilityTranscriptionOnly,
				speechkit.CapabilityTranscript,
				speechkit.CapabilityInterruptions,
				speechkit.CapabilitySessionSummary,
			},
			SupportedLocales: []string{"*"},
			NativeOptions:    []string{"context_prompt", "reasoning_effort", "turn_detection", "transcription_only", "translation"},
			AuthRequirement:  "api_key",
			Transport:        "websocket",
			EvidenceURL:      "https://learn.microsoft.com/azure/ai-foundry/openai/realtime-audio-quickstart",
			AdapterKind:      "foundry_realtime",
			Variants: []speechkit.ModelVariant{
				{ID: "foundry.gpt-realtime-2", Name: "GPT Realtime 2", ModelID: ModelOpenAIRealtime2, Recommended: true},
				{ID: "foundry.gpt-realtime-2.1", Name: "GPT Realtime 2.1 (Preview)", ModelID: "gpt-realtime-2.1"},
				{ID: "foundry.gpt-realtime-2.1-mini", Name: "GPT Realtime 2.1 mini (Preview)", ModelID: "gpt-realtime-2.1-mini"},
			},
			AllowInference: true,
			Recommended:    true,
		},
		{
			// Voice Live is Microsoft's managed voice agent on the same Foundry
			// resource: the brain is any of the models the service hosts (no
			// deployment needed), speech in comes from MAI-Transcribe, speech
			// out from a MAI-Voice-2 voice, with Azure semantic VAD, noise
			// suppression and echo cancellation on the server. The model id is
			// the brain; voice and transcription live in the Foundry settings.
			ID:            "realtime.foundry.voice-live",
			Mode:          speechkit.ModeVoiceAgent,
			Name:          "Microsoft Foundry Voice Live",
			ProviderKind:  speechkit.ProviderKindDirectProvider,
			ExecutionMode: speechkit.ExecutionModeFoundry,
			Provider:      "foundry-voicelive",
			ModelID:       "gpt-realtime-2",
			Lifecycle:     speechkit.ModelLifecycleGA,
			Source:        "Microsoft Foundry",
			Description:   "Microsoft-native realtime voice agent: Voice Live pairs a hosted brain model with MAI-Voice-2 speech output and MAI-Transcribe-2 input transcription, plus server-side semantic turn detection and noise suppression. The MAI voice and transcription models are public preview.",
			License:       "proprietary",
			Capabilities: []speechkit.Capability{
				speechkit.CapabilityAudioInput,
				speechkit.CapabilityRealtimeAudio,
				speechkit.CapabilityToolCalling,
				speechkit.CapabilityNativeContextPrompt,
				speechkit.CapabilityTranscript,
				speechkit.CapabilityInterruptions,
				speechkit.CapabilitySessionSummary,
			},
			SupportedLocales: []string{"*"},
			NativeOptions:    []string{"context_prompt", "turn_detection"},
			AuthRequirement:  "api_key",
			Transport:        "websocket",
			EvidenceURL:      "https://learn.microsoft.com/azure/ai-services/speech-service/voice-live",
			AdapterKind:      "foundry_voicelive",
			Variants: []speechkit.ModelVariant{
				{ID: "foundry.voicelive.gpt-realtime-2", Name: "GPT Realtime 2 brain", ModelID: "gpt-realtime-2", Recommended: true},
				{ID: "foundry.voicelive.gpt-realtime-mini", Name: "GPT Realtime mini brain", ModelID: "gpt-realtime-mini", Description: "Lower cost realtime brain."},
				{ID: "foundry.voicelive.gpt-5.4", Name: "GPT-5.4 brain", ModelID: "gpt-5.4", Description: "Newest text brain the Voice Live service hosts itself; speech in and out come from the service."},
				{ID: "foundry.voicelive.phi4-mm-realtime", Name: "Phi-4 multimodal realtime brain", ModelID: "phi4-mm-realtime", Description: "Small Microsoft model for low-latency agents."},
			},
			AllowInference: true,
			Recommended:    true,
		},
	}
}
