import type {
  ModelSelectionsState,
  SpeechKitOverlayState,
  SpeechKitSettingsState,
  VoiceAgentProfile,
  WakewordSettings,
} from "./types";

// defaultWakewordSettings mirrors the empty-state of the backend's
// WakewordConfig defaults (cfg.Wakeword in internal/config/defaults.go).
// The phraseCatalog stays empty until /settings/state is fetched — the
// backend ships the curated list at that point so the UI dropdown can
// render the four+ shipped entries (hey_quby / hey_computer / hey_jarvis
// / hey_mira / hey_kombify).
export const defaultWakewordSettings: WakewordSettings = {
  enabled: false,
  backend: "livekit_openwakeword",
  phraseId: "hey_quby",
  defaultMode: "voice_agent",
  threshold: 0,
  minConsecutiveFrames: 1,
  cooldownMs: 1500,
  debugMode: false,
  active: false,
  statusMessage: "",
  phraseCatalog: [],
  backendOptions: [
    {
      id: "livekit_openwakeword",
      label: "openWakeWord (per-phrase trained)",
      description: "",
      status: "",
      available: false,
      implemented: true,
      recommended: true,
    },
    {
      id: "sherpa_kws",
      label: "Sherpa KWS (generic Gigaspeech)",
      description: "",
      status: "",
      available: false,
      implemented: true,
    },
    {
      id: "stt_phrase",
      label: "STT phrase match",
      description: "",
      status: "",
      available: false,
      implemented: true,
    },
  ],
};

export const builtInPrimaryModelSelections: ModelSelectionsState = {
  dictate: { primaryProfileId: "stt.local.whispercpp", fallbackProfileId: "" },
  assist: {
    primaryProfileId: "assist.builtin.gemma4-e4b",
    fallbackProfileId: "",
  },
  voice_agent: {
    primaryProfileId: "realtime.builtin.pipeline",
    fallbackProfileId: "",
  },
};

export const defaultVoiceAgentProfiles: VoiceAgentProfile[] = [
  {
    id: "default",
    displayName: "Default Voice Agent",
    description: "Current Voice Mode behavior.",
    builtIn: true,
  },
  {
    id: "brainstorming_companion",
    displayName: "Brainstorming Companion",
    description: "Creative sparring partner for broader, critical thinking.",
    voice: "Aoede",
    builtIn: true,
  },
  {
    id: "humor_companion",
    displayName: "Humor Companion",
    description: "Playful, entertaining voice conversation.",
    voice: "Puck",
    builtIn: true,
  },
  {
    id: "support_companion",
    displayName: "Support Companion",
    description: "Warm, solution-oriented help with emotional awareness.",
    voice: "Charon",
    builtIn: true,
  },
];

export const defaultOverlayState: SpeechKitOverlayState = {
  state: "idle",
  phase: "idle",
  text: "",
  level: 0,
  visible: true,
  visualizer: "pill",
  design: "default",
  assistOverlayMode: "small_feedback",
  voiceAgentOverlayMode: "small_feedback",
  hotkey: "ctrl+win",
  dictateHotkey: "ctrl+win",
  assistHotkey: "win+alt",
  voiceAgentHotkey: "ctrl+shift",
  dictateHotkeyBehavior: "hold_to_talk",
  assistHotkeyBehavior: "hold_to_talk",
  voiceAgentHotkeyBehavior: "hold_to_talk",
  modeEnabled: {
    dictate: true,
    assist: true,
    voice_agent: true,
  },
  agentHotkey: "win+alt",
  activeMode: "none",
  availableModes: {
    dictate: true,
    assist: true,
    voice_agent: true,
  },
  position: "bottom",
  movable: false,
  positionFreeX: 0,
  positionFreeY: 0,
  lastTranscription: "",
  quickNoteMode: false,
  selectedAudioDeviceId: "",
  selectedOutputDeviceId: "",
  activeProfiles: {},
};

export const defaultSettingsState: SpeechKitSettingsState = {
  overlayEnabled: true,
  storeBackend: "sqlite",
  sqlitePath: "",
  postgresConfigured: false,
  postgresDSN: "",
  maxAudioStorageMB: 500,
  modelDownloadDir: "",
  hfAvailable: false,
  hfEnabled: false,
  hfHasUserToken: false,
  hfHasInstallToken: false,
  hfTokenSource: "none",
  hotkey: "ctrl+win",
  dictateHotkey: "ctrl+win",
  assistHotkey: "win+alt",
  voiceAgentHotkey: "ctrl+shift",
  dictateHotkeyBehavior: "hold_to_talk",
  assistHotkeyBehavior: "hold_to_talk",
  voiceAgentHotkeyBehavior: "hold_to_talk",
  voiceAgentCloseBehavior: "continue",
  voiceAgentProfileId: "default",
  voiceAgentProfiles: defaultVoiceAgentProfiles,
  voiceAgentRefinementPrompt: "",
  voiceAgentSessionSummary: true,
  autoStartOnLaunch: false,
  modeEnabled: {
    dictate: true,
    assist: true,
    voice_agent: true,
  },
  agentHotkey: "win+alt",
  agentMode: "assist",
  activeMode: "none",
  availableModes: {
    dictate: true,
    assist: true,
    voice_agent: true,
  },
  hfModel: "openai/whisper-large-v3-turbo",
  visualizer: "pill",
  design: "default",
  assistOverlayMode: "small_feedback",
  voiceAgentOverlayMode: "small_feedback",
  overlayPosition: "bottom",
  overlayMovable: false,
  overlayFreeX: 0,
  overlayFreeY: 0,
  vocabularyDictionary: "",
  saveAudio: true,
  audioRetentionDays: 7,
  dictateSilenceTimeoutSec: 3,
  selectedAudioDeviceId: "",
  selectedOutputDeviceId: "",
  activeProfiles: {},
  modelSelections: builtInPrimaryModelSelections,
  wakeword: defaultWakewordSettings,
  homeAssistant: {
    url: "",
    tokenEnv: "",
    tokenConfigured: false,
    language: "",
  },
  piperTTS: {
    enabled: false,
    binary: "",
    voiceDir: "",
    timeoutSec: 0,
    defaultVoices: {},
    availableVoices: [],
  },
};
