import { defaultWakewordSettings } from "@/lib/speechkit";
import type { SpeechKitSettingsState } from "@/lib/speechkit";

export const baseSettings: SpeechKitSettingsState = {
  overlayEnabled: true,
  storeBackend: "sqlite",
  sqlitePath: "C:/Users/testuser/AppData/Roaming/SpeechKit/feedback.db",
  postgresConfigured: false,
  postgresDSN: "",
  maxAudioStorageMB: 500,
  hfAvailable: true,
  hfEnabled: false,
  hotkey: "ctrl+win",
  dictateHotkey: "ctrl+win",
  assistHotkey: "win+alt",
  voiceAgentHotkey: "ctrl+shift",
  dictateHotkeyBehavior: "hold_to_talk",
  assistHotkeyBehavior: "hold_to_talk",
  voiceAgentHotkeyBehavior: "hold_to_talk",
  voiceAgentCloseBehavior: "continue",
  voiceAgentProfileId: "default",
  voiceAgentProfiles: [
    {
      id: "default",
      displayName: "Default Voice Agent",
      description: "Current Voice Mode behavior.",
    },
    {
      id: "brainstorming_companion",
      displayName: "Brainstorming Companion",
      description: "Critical, creative ideation partner.",
      voice: "Aoede",
    },
    {
      id: "humor_companion",
      displayName: "Humor Companion",
      description: "Playful conversation profile.",
      voice: "Puck",
    },
    {
      id: "support_companion",
      displayName: "Support Companion",
      description: "Warm, solution-oriented helper.",
      voice: "Charon",
    },
  ],
  voiceAgentRefinementPrompt: "",
  voiceAgentSessionSummary: true,
  autoStartOnLaunch: false,
  agentHotkey: "win+alt",
  agentMode: "assist",
  activeMode: "none",
  modeEnabled: {
    dictate: true,
    assist: true,
    voice_agent: true,
  },
  availableModes: {
    dictate: true,
    assist: true,
    voice_agent: true,
  },
  hfModel: "openai/whisper-large-v3-turbo",
  visualizer: "pill",
  design: "default",
  assistOverlayMode: "small_feedback",
  voiceAgentOverlayMode: "small_feedback",
  overlayPosition: "top",
  overlayMovable: false,
  overlayFreeX: 0,
  overlayFreeY: 0,
  modelDownloadDir: "C:/Users/testuser/AppData/Local/SpeechKit/models",
  vocabularyDictionary: "",
  saveAudio: true,
  audioRetentionDays: 7,
  dictateSilenceTimeoutSec: 10,
  selectedAudioDeviceId: "mic-1",
  hfHasUserToken: false,
  hfHasInstallToken: false,
  hfTokenSource: "none",
  activeProfiles: { stt: "stt-local" },
  modelSelections: {
    dictate: { primaryProfileId: "stt-local", fallbackProfileId: "" },
    assist: {
      primaryProfileId: "assist.builtin.gemma4-e4b",
      fallbackProfileId: "",
    },
    voice_agent: {
      primaryProfileId: "realtime.google.gemini-native-audio",
      fallbackProfileId: "",
    },
  },
  profiles: [
    {
      id: "stt-local",
      modality: "stt",
      name: "Qwen/Qwen3-ASR-1.7B",
      executionMode: "local",
      description: "Default local STT profile",
    },
  ],
  providerCredentials: {
    huggingface: {
      provider: "huggingface",
      label: "Hugging Face",
      envName: "HF_TOKEN",
      available: true,
      hasStoredSecret: false,
      source: "none",
    },
  },
  wakeword: defaultWakewordSettings,
  homeAssistant: {
    url: "",
    tokenEnv: "",
    tokenConfigured: false,
    language: "",
  },
  piperTTS: {
    enabled: false,
    binary: "",
    voiceDir: "",
    timeoutSec: 0,
    defaultVoices: {},
    availableVoices: [],
  },
};
